### ISSUE TITLE
Performance regression in the classpath lookup

### ISSUE THREAD

**Issue by gkossakowski** [sbt/zinc#100]
The performance of classpath lookup has regressed in both sbt and zinc. The performance is lost due to a repeated calls to `FileValueCache.get` that performs a filesystem call to see if a corresponding file has changed and the cache entry needs to be invalidated.

The cached values are partially applied function `DefinesClass` that is an alias for `File => String => Boolean`. The `FileValueCache` caches `String => Boolean` functions based on a given file. The file here corresponds to a classpath element (e.g. directory or a jar). In sbt 0.13.11, the values from the cache are fetched in this code:

``` scala
/**
   * Returns a function that searches the provided class path for
   * a class name and returns the entry that defines that class.
   */
  def entry(classpath: Seq[File], f: DefinesClass): String => Option[File] =
    {
      val entries = classpath.toStream.map { entry => (entry, f(entry)) }
      className => entries.collect { case (entry, defines) if defines(className) => entry }.headOption
    }
```

Here, the argument `f` is a function roughly of the shape `(file: File) => FileValueCache.get(file)`. The first line looks up (lazily because it's a Stream) cached functions from the `FileValueCache`. The returned function in the second line closes over `entries`. The end result is that `entry` returns a function that closes over a series of functions that were looked up from `FileValueCache`.

Now, in zinc and sbt 1.0 the function `f` passed to the `entry` method is roughly of the shape `(file: File) => (className: String) => FileValueCache.get(file)(className)`. When you apply this function with a file in the `entries` definition, you'll just get another function `g` that _closes_ over `file` value but doesn't call the cache yet. The cache is called only when `className` is passed to `g` - that's is the cache is hit on every classpath lookup. The delayed evaluation of the `File` argument was introduced twice: once on the zinc side and second time on the sbt side. In both cases it's due to wrapping to accommodate to Java API.

The regression in zinc occurred at https://github.com/sbt/zinc/commit/9c75003b3129400b1ee3b8a16d1792132f776594#diff-f07388b6f3520add59fb517e7d3f530aR38.
The sbt regression was introduced at https://github.com/sbt/sbt/commit/20d0c41473f515cf94ebbc5ac9d59e2602284b76#diff-6373e7f7122325e753b75fe1cc76ff5fR878

**Comment by gkossakowski** [comment]
Introduction of the same bug twice by two different people suggests that using currying for caching is not a good idea. If the evaluation order is important, one should signal it with distinctive types and proper documentation.

**Comment by gkossakowski** [comment]
This patch fixes the problem on the zinc side:

``` patch
diff --git a/zinc/src/main/scala/sbt/internal/inc/IncrementalCompilerImpl.scala b/zinc/src/main/scala/sbt/internal/inc/IncrementalCompilerImpl.scala
index 7c2e217..fbeae8d 100644
--- a/zinc/src/main/scala/sbt/internal/inc/IncrementalCompilerImpl.scala
+++ b/zinc/src/main/scala/sbt/internal/inc/IncrementalCompilerImpl.scala
@@ -44,7 +44,10 @@ class IncrementalCompilerImpl extends IncrementalCompiler {
         m2o(in.previousResult.analysis),
         m2o(in.previousResult.setup),
         { f => m2o(analysisMap()(f)) },
-        { f => { s => definesClass()(f)(s) } },
+        { f =>
+          val dc = definesClass()(f)
+          s => dc(s)
+        },
         reporter, order, skip, incrementalCompilerOptions,
         extra.toList map { x => (x.get1, x.get2) })(log)
     }
```

but I think comprehension level of the code responsible for classpath lookups dropped below acceptable threshold. I'll rework it.

**Comment by stuhood** [comment]
> Introduction of the same bug twice by two different people suggests that using currying for caching is not a good idea. If the evaluation order is important, one should signal it with distinctive types and proper documentation.

+1000

**Comment by eed3si9n** [comment]
I suggest we fix this one way or the other before M1.

**Comment by gkossakowski** [comment]
I'll post an ugly fix soon so we can release M1. The refactoring will probably a bit more effort to prepare.

**Comment by gkossakowski** [comment]
I refactored how Definesclass lookup is done in #120
