### ISSUE TITLE
Get rid of SimpleType, everything should just be a Type

### ISSUE THREAD

**Issue by smarter** [sbt/zinc#101]
Cf https://github.com/sbt/zinc/blob/1.0/internal/compiler-interface/src/main/contraband/type.json

`Structure` is not a subtype of `SimpleType` but `Projection#prefix` has to be a simple type this means that sbt cannot represent something like `(Foo { type T })#T` (the prefix is replaced by the empty type in [`simpleType`](https://github.com/sbt/zinc/blob/088a577149b0803b19dcec4f984d4035c5e4fc7b/internal/compiler-bridge/src/main/scala/xsbt/ExtractAPI.scala#L173-L177)).

I think we should just get rid of the `SimpleType`/`Type` separation, it's not useful.

**Comment by eed3si9n** [comment]
Related, on https://groups.google.com/d/msg/scala-internals/ANcaI6dVYPw/2Gt5z_S3Gc0J via sbt/sbt#830 Martin wrote:

>  As everybody has already guessed, SimpleTypes are a pure parsing construct. Inside the parens they can be as complex as you like.

**Comment by jvican** [comment]
@smarter your student is working on this, right?

**Comment by smarter** [comment]
Yes.

On Mar 3, 2017 17:34, "Jorge" <notifications@github.com> wrote:

@smarter <https://github.com/smarter> your student is working on this,
right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sbt/zinc/issues/101#issuecomment-283896560>, or mute
the thread
