### ISSUE TITLE
HashUtil.farmHash leads to OOME with large files

### ISSUE THREAD

**Issue by niktrop** [sbt/zinc#1015]
## steps
Checkout https://github.com/JetBrains/intellij-scala
Remove this line:
https://github.com/JetBrains/intellij-scala/blob/ae3cb5fe8b1c03ed2e4d3c5c4631e8e62e5ef4be/build.sbt#L27
`sbt compile`

## problem
Sbt allocates byte arrays in `HashUtil.farmHash(path: Path)` method. In case of many concurrent tasks and large files it may lead to OOME:

[error] ## Exception when compiling 0 sources to C:\Users\Nikolay.Tropin\IdeaProjects1\intellij-scala2\pluginXml\target\scala-2.13\classes
[error] ## Exception when compiling 30 sources to C:\Users\Nikolay.Tropin\IdeaProjects1\intellij-scala2\scala\dfa\target\scala-2.13\classes
[error] java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[error] java.lang.OutOfMemoryError: Java heap space
[error] java.lang.OutOfMemoryError: Java heap space
[error] java.base/java.nio.file.Files.read(Files.java:3221)
[error] java.base/java.nio.file.Files.read(Files.java:3221)
[error] java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
[error] java.base/java.nio.file.Files.readAllBytes(Files.java:3278)
[error] java.base/java.nio.file.Files.readAllBytes(Files.java:3278)
[info] shutting down sbt server
[error] sbt.internal.inc.HashUtil$.farmHash(HashUtil.scala:24)
[error] sbt.internal.inc.HashUtil$.farmHash(HashUtil.scala:24)
java.lang.OutOfMemoryError: Java heap space
Error during sbt execution: java.lang.OutOfMemoryError: Java heap space

## expectation
No crash 😄 

## notes
This version produces the same hash without copying file content to the heap. It also seem to work faster, at least for large files.
```
import java.nio.ByteBuffer
import java.nio.channels.FileChannel
import java.nio.file.StandardOpenOption

def farmHash(buffer: ByteBuffer): Long =
  LongHashFunction.farmNa().hashBytes(buffer)

def farmHash(path: Path): Long =
  farmHash(mappedBuffer(path))

private def mappedBuffer(path: Path): ByteBuffer = {
  val fileChannel = FileChannel.open(path, StandardOpenOption.READ)
  fileChannel.map(FileChannel.MapMode.READ_ONLY, 0, fileChannel.size())
}
```

**Comment by eed3si9n** [comment]
Thanks for the report and a fix suggestion. Would you like to send a PR for it?

**Comment by eed3si9n** [comment]
Here's the PR - https://github.com/sbt/zinc/pull/1016

**Comment by eed3si9n** [comment]
The test failed (I repeated it a few times)

**Comment by niktrop** [comment]
I guess it's some JVM bug, it fails only with jdk 1.8. But probably it's better to avoid this API.

Is it necessary to keep hash value consistent between sbt versions? I would keep the current function for smaller files and use some stream hashing (like `sbt.io.Hash`) for large ones.

**Comment by eed3si9n** [comment]
I don't think it's necessary to keep the hash between the sbt versions since it's an implementation detail, but we might not do that on a patch version.
