### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by RiRa12621** [sbt/zinc#1021]
Hey team,
Is it possible for you to craft a new bug fix release?
I know, that releasing things ad-hoc isn't great fun and a bit of a wild ask, but it'd be great to receive a release that includes a fix also for the latest log4j vulnerability, which has been fixed in 2.17.1.

If I understand correctly, the fix lives on the dev branch already since https://github.com/sbt/zinc/pull/1019

Thank you

**Comment by eed3si9n** [comment]
https://github.com/sbt/zinc/releases/tag/v1.6.1 is on its way to Maven Cental.

**Comment by RiRa12621** [comment]
Thanks! That's much appreciated
