### ISSUE TITLE
CONTRIBUTING.md references Gitter

### ISSUE THREAD

**Issue by SethTisue** [sbt/zinc#1027]
```
% git grep -i gitter
CONTRIBUTING.md:please let us know in our Gitter room [sbt/zinc-contrib][].
CONTRIBUTING.md:[sbt/zinc-contrib]: https://gitter.im/sbt/zinc-contrib
```

@eed3si9n I'd fix it but I don't actually know what info you want included instead.

(or, maybe I'm wrong to assume you want to ditch that Gitter room...)

**Comment by eed3si9n** [comment]
I would like to ditch all Gitter rooms. I can't make commitment to be in any chat rooms, so we should probably remove the reference.

**Comment by SethTisue** [comment]
PR: #1030

I also enabled Discussions in this repo: https://github.com/sbt/zinc/discussions
