### ISSUE TITLE
Compiled scala throws java.lang.VerifyError

### ISSUE THREAD

**Issue by Sineaggi** [sbt/zinc#1035]
## steps

When migrating from sbt to gradle, we encountered a case where the scala compiler generates code that java doesn't like. In this case it's a routes file that would generate thousands of classes.

While investing the compiler output difference, we noticed that the only difference between the classfile being loadable and not was the java major version in the header (the file compiled under sbt had the header `CAFEBABE 00000032` and the file compiled under gradle had the header  `CAFEBABE 00000034`). This would have me believe that under java 8, the classfile is checked more strictly when the class is loaded.

In this case the input routes_routing.scala file is around 9000 lines long, and generates around 4000 classes.

I loaded each class via Class.forName to see which ones throw with this verify error, and there's only one class that fails to load, the play `Routes$$anonfun$routes$1` class.

## problem

When running the play application, we see the output
```
2022-02-03 21:52:43,369 - [] [] [::] [ERROR] - from application in New I/O worker #2
Error while rendering default error page
scala.MatchError: java.lang.VerifyError: StackMapTable error: bad offset
Exception Details:
  Location:
    Routes$$anonfun$routes$1.applyOrElse(Lplay/api/mvc/RequestHeader;Lscala/Function1;)Ljava/lang/Object; @0: aload_1
  Reason:
    Invalid stackmap specification.
  Current Frame:
    bci: @65536
    flags: { }
    locals: { 'Routes$$anonfun$routes$1', 'play/api/mvc/RequestHeader', 'scala/Function1', 'play/api/mvc/RequestHeader', 'scala/Option', top, top, 'scala/Option' }
    stack: { }
  Bytecode:
```

## expectation

Just like when compiled by sbt, the code should load and work.
EDIT: Preferably the code generated by the compiler should work on any target jvm.

## notes

Since the only difference between java being happy with the class and throwing is the java major version header, I was able to work around this by setting the target jvm to 1.6.

```kotlin
tasks.withType<ScalaCompile>().configureEach {
    scalaCompileOptions.additionalParameters = listOf("-target:jvm-1.6")
}
```

According to `./gradlew dependencies` the zinc compiler used is 
```
zinc - The Zinc incremental compiler to be used for this Scala project.
+--- org.scala-sbt:zinc_2.12:1.3.5
```
I'm running on gradle 7.3.3

**Comment by Sineaggi** [comment]
Perhaps this is in the wrong repo? I guess it's more relevant to the scala-compiler library than zinc, maybe?

**Comment by Sineaggi** [comment]
Regardless, a project that will reproduce the issue is here https://github.com/Sineaggi/scala-repro
To run it, run `./gradlew runPlay` and then hit localhost:9000
The VerifyError should show up in the logs.

**Comment by Sineaggi** [comment]
The one file that you can copy to any project and run `Class.forName()` that will fail with a VerifyError is
[Routes$anonfun$routes$1.class.zip](https://github.com/sbt/zinc/files/8007128/Routes.anonfun.routes.1.class.zip)
 this class.

**Comment by eed3si9n** [comment]
> Perhaps this is in the wrong repo?

@Sineaggi Thanks for the report. If the build works correctly when built using sbt but fails if you use Gradle, I am failing to understand how this is anything but a Gradle issue (or Gradle Play Plugin?).

Also for future reference, in "steps" section (https://github.com/sbt/zinc/blob/develop/CONTRIBUTING.md#steps), what we are looking for is:

> **the exact steps to reproduce your problems on our computers**

Everything you described in the "steps", I would move to "notes" section. The actual steps seems like:

```bash
git clone https://github.com/Sineaggi/scala-repro.git
./gradlew runPlay
```

After some investigation, Gradle Play Plugin project or other contributors may find something in Zinc that's incorrectly producing some bytecode, but I don't think it's Zinc's responsibility to find out how they might be holding Zinc wrong.

**Comment by Sineaggi** [comment]
Sorry, I should have mentioned that this is also reproducible in sbt.

I've pushed a build.sbt file [here](https://github.com/Sineaggi/scala-repro/commit/b9da241f5e96dbb07ce93fe018a60cd53ae4b126) that will reproduce the issue, run with `sbt run` and then load localhost:9000, just like with gradle.

**Comment by eed3si9n** [comment]
It sounds like you're hitting https://github.com/scala/bug/issues/10609 since it seems to go away after downgrading Scala version to 2.11.11.

**Comment by Sineaggi** [comment]
> It sounds like you're hitting [scala/bug#10609](https://github.com/scala/bug/issues/10609) since it seems to go away after downgrading Scala version to 2.11.11.

I can't say that that exact issue is what I'm encountering but you're right, downgrading to 2.11.11 fixes it. Clearly I had some differences between sbt and gradle that caused this to show up.

Thanks for finding that bug report!

Interesting though that the fix posted by @retronym was to use `-target:jvm-1.8`, whereas in my case forcing `-target:jvm-1.6` was the only fix.
