### ISSUE TITLE
Duplication between this repository and scala/compiler-interface

### ISSUE THREAD

**Issue by smarter** [sbt/zinc#1080]
Some files exist in both projects:
- https://github.com/scala/compiler-interface/blob/develop/compiler-interface/src/main/java/scala/tools/sci/VirtualFile.java
- https://github.com/sbt/zinc/blob/develop/internal/compiler-interface/src/main/java/xsbti/VirtualFile.java

Is scala/compiler-interface actually used, or was it an experimental attempt at splitting the compiler-interface in a separate repo that was never finished? If the latter, it'd be good to archive the repo to avoid confusion.

**Comment by eed3si9n** [comment]
Yea, I think there was some intent for it, but pandemic happened and it got dropped on the floor?

**Comment by smarter** [comment]
Closing this since compiler-interface has been archived.
