### ISSUE TITLE
Source locations are formatted as offsets instead of line+column.

### ISSUE THREAD

**Issue by DSouzaM** [sbt/zinc#1089]
## steps

Compile a Scala project containing syntax/type errors. I'm using the scala-maven-plugin (version 4.6.1), which invokes the Zinc incremental compiler. 

## problem

The error message, printed by zinc, formats the position of the error as a file offset:
```
[ERROR] /Users/matt/.../Foo.scala:[14783..14793..14799]: type HahMap is not a member of java.util - did you mean util.HashMap?
```

(I think it's printing the Dotty `SourcePosition`, because the output matches the `toString` method [here](https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/util/SourcePosition.scala#L83-L84))

## expectation

It would be more useful to developers to print the error location as a pair of `line:col`.

## notes

I wonder if this is possible just with different `CompileOptions`. I'm not a `scala-maven-plugin` developer but have debugged an execution of the plugin right until the `compile` call ([source](https://github.com/davidB/scala-maven-plugin/blob/master/src/main/java/sbt_inc/SbtIncrementalCompiler.java#L179)), which is where the error gets printed and an exception is thrown. I would be willing to submit a change to the plugin if there's an appropriate option that could be changed.

**Comment by eed3si9n** [comment]
In general, I think Zinc mostly uses `CompileFailed` exception as a mechanism to communicate with the build tool that the compilation has failed, and the build tool should take an appropriate action without printing the `toString`.
The compilation errors and warning should be coming through the reporter.

Regardless, if you think `toString` should be changed, perhaps the issue should be opened against Scala 3 compiler?

**Comment by adpi2** [comment]
@DSouzaM thanks for reporting this!

Here is a fix in the Scala 3 sbt bridge: https://github.com/lampepfl/dotty/pull/14910

If you also want to fix it in scala-maven-plugin, for existing versions of Scala 3, you can replace the `LoggedReporter` [here](https://github.com/davidB/scala-maven-plugin/blob/c0abc9cc57637b6615ca22dd12adb92f3259d2aa/src/main/java/sbt_inc/SbtIncrementalCompiler.java#L132) with some `CustomReporter` defined as:

```scala
class CustomReporter(
    logger: ManagedLogger
) extends LoggedReporter(100, logger, identity) {
  override def logError(problem: Problem): Unit = logger.error(customToString(problem))
  override def logWarning(problem: Problem): Unit = logger.warn(customToString(problem))
  override def logInfo(problem: Problem): Unit = logger.info(customToString(problem))

  private def customToString(problem: Problem): String = // define your own toString for Problem
}
```

**Comment by DSouzaM** [comment]
This is great, thank you! I was just about to go down that route.

**Comment by smarter** [comment]
I think the root of the issue is the use of LoggedReporter in scala-maven-plugin as @adpi2 pointed out. But instead of making a custom reporter, I think ManagedLoggedReporter could be used, the key difference is that it is setup to pretty-print error messages specially: https://github.com/sbt/zinc/blob/c550e78216d159d7ebd495100792be292b27874e/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/LoggedReporter.scala#L84

So I think you can just change `LoggedReporter` to `ManagedLoggedReporter` in https://github.com/davidB/scala-maven-plugin/blob/c0abc9cc57637b6615ca22dd12adb92f3259d2aa/src/main/java/sbt_inc/SbtIncrementalCompiler.java#L132 and get the same output sbt will get (which should be much nicer than the current output based on toString, even if we fix toString!)

**Comment by DSouzaM** [comment]
Thanks @smarter. I tried your suggestion, but `ManagedLoggedReporter` requires a `ManagedLogger`. I grepped around the code, but I can't find a way to instantiate a `ManagedLogger` (the constructor takes a `MiniLogger`, which is package-private). Any tips?

**Comment by smarter** [comment]
Ah sorry, I didn't realize that, it looks like this is doable with some more boilerplate as seen in mill:
https://github.com/com-lihaoyi/mill/blob/06839184facbc3d3d19e9a7fec95575f0ff73d98/scalalib/worker/src/mill/scalalib/worker/ZincWorkerImpl.scala#L415-L429
Try directly copy-pasting that (and adding the necessary imports for ConsoleAppender, etc), `ctx.log.errorStream` can be replaced by `System.err` and `ctx.log.colored` can be replaced by `true`.
