### ISSUE TITLE
This line seems to contain a bug: if classpathEntry turns out to be a directory, this comparison unsurprisingly always fails:

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#1140]
## original description

        This line seems to contain a bug: if classpathEntry turns out to be a directory, this comparison unsurprisingly always fails:
```
Invalidating '.../build/classes/scala/main/.../Foo.class' because
 .../build/classes/scala/main/....class (farm(77c283a23fed88f2)) != .../build/classes/scala/main (absent)
                                                                         ^^^ RHS is a ***directory***.
```
The `resolve` step was completely dropped in this PR.

_Originally posted by @mernst-github in https://github.com/sbt/zinc/pull/712#discussion_r1002970496_

**Comment by tnielens-centrica** [comment]
We are facing productivity issues in a gradle multi-project repo with several small gradle subprojects with the plugin `java-library` applied. @mernst-github @tgodzik, would you know a workaround for this? Would a zinc downgrade help?

**Comment by mernst-github** [comment]
Try enabling https://github.com/sbt/zinc/blob/develop/internal/zinc-core/src/main/scala/sbt/internal/inc/IncrementalCommon.scala#L46 in the `compileScala.scalaCompileOptions.forkOptions`.

**Comment by tnielens-centrica** [comment]
Seems to be working for us. Thanks 🙏
