### ISSUE TITLE
Private var in trait

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#118]
Pending test: https://github.com/sbt/zinc/tree/0cbb8e65c2cd1dff6bea983799f22cbcf2cf5091/zinc/src/sbt-test/source-dependencies/trait-private-var, sbt/sbt@c6b0043336a48c713eec5202fc6ef88006c5275b
Related bug report(s): sbt/sbt#2155, sbt/sbt#2490
Fix in 0.13: https://github.com/sbt/sbt/pull/2441

**Comment by dwijnand** [comment]
Closing if favour of the more commented #292.
