### ISSUE TITLE
Don't publish repositories information (at least for releases)

### ISSUE THREAD

**Issue by gslowikowski** [sbt/zinc#119]
Remove all additional resolvers from `build.sbt`, at least for releases, because artifacts published to Maven central repository should not contain additional repositories, and in fact don't need them because all dependencies are already in Maven central repo.

**Comment by jvican** [comment]
Do you have something to say on this? @gslowikowski is suggesting to remove `addSbtAlternateResolver` but I don't really know why that resolver was added in the first place.

**Comment by jvican** [comment]
This will be done when https://github.com/sbt/zinc/pull/429 lands.
