### ISSUE TITLE
IncOptions.useOptimizedSealed is broken on 2.13

### ISSUE THREAD

**Issue by smarter** [sbt/zinc#1229]
build.sbt:
```scala
lazy val root = (project in file(".")).
  settings(
    name := "sbt-hello",
    scalaVersion := "2.13.11"
  )
ThisBuild / incOptions ~= { _.withUseOptimizedSealed(true) }
```

Sealed.scala:
```scala
sealed trait Sealed
class Child1 extends Sealed
```

PatMat.scala:
```scala
object PatMat {
  def test(x: Sealed): Int = x match {
    case _: Child1 => 1
  }
}
```

1. `compile`
2. Add an extra child in Sealed.scala: `class Child2 extends Sealed`
3. `compile` again, only Sealed.scala is recompiled.

If I change `scalaVersion` to `2.12.18`, then `PatMat.scala` is recompiled as expected.
I assume the zinc scripted tests such as https://github.com/sbt/zinc/tree/develop/zinc/src/sbt-test/source-dependencies/patMat-scope only run with 2.12, it'd be great to run them with 2.13 too to catch this sort of issues.

/cc @retronym who might be aware of projects that use `useOptimizedSealed`.

**Comment by lrytz** [comment]
Fixed in https://github.com/sbt/zinc/pull/1278
