### ISSUE TITLE
ArrayStoreException when parsing Java annotation

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#123]
https://github.com/sbt/sbt/issues/756 
@dotta wrote:

> Alright, I actually found a way to reproduce this! (Using sbt 0.13.0)
> - Clone https://github.com/dotta/sbt-issue-756 and checkout commit dotta/sbt-issue-756@ddc49b2
> - Start sbt console and then ~test. Compilation should succeed.
> - Apply this commit dotta/sbt-issue-756@6c8ffef
> - You would expect compilation to fail, but it doesn't!
>   
>   To make it fail, you need to clean first.

**Comment by jvican** [comment]
All the information about this ticket is https://github.com/sbt/sbt/issues/756. Ping me in Gitter if you need more info on this.

**Comment by jvican** [comment]
I'm not even sure this is an error anymore, but a volunteer can get the reproduced example in the linked ticket and assert so.

**Comment by senia-psm** [comment]
I've encountered this issue in my project.
Here is my minimized example in case someone needs it: https://github.com/senia-psm/zinc-issues-123

**Comment by Friendseeker** [comment]
```
[info] set current project to zinc-issues-123 (in build file:/Users/jiahuitan/zinc-issues-123/)
[IJ]clean
[success] Total time: 0 s, completed Oct 2, 2024, 6:49:52 p.m.
[IJ]compile
[info] compiling 1 Java source to /Users/jiahuitan/zinc-issues-123/target/scala-2.12/classes ...
[info] done compiling
[success] Total time: 1 s, completed Oct 2, 2024, 6:49:54 p.m.
```

Probably fixed by Seth's java annotations PRs
