### ISSUE TITLE
java records not supported

### ISSUE THREAD

**Issue by tballard** [sbt/zinc#1238]
To reproduce: Put a record in your java code and try compiling.  

It's been in the language since java 14. I don't know what version you try to support but this will be appreciated.

**Comment by SethTisue** [comment]
this is a Scala compiler issue — nothing to do with zinc, which only adds incremental compilation abilities to the stock Scala 2 compiler

what version of Scala are you using? in Scala 2, support landed in Scala 2.13.7: https://github.com/scala/scala/pull/9551. in Scala 3, support is in 3.3.1-RC5, and will land in a stable release in 3.3.1, as per https://github.com/lampepfl/dotty/pull/16762

**Comment by tballard** [comment]
I was switching to scala 3, now that you mention it. Sounds like it's under control. Thank you for your efforts.
