### ISSUE TITLE
Scala 3: Incremental compilation bug with top-level definitions

### ISSUE THREAD

**Issue by mberndt123** [sbt/zinc#1239]
Hey,

When you add a new Scala source file with a `def` that makes an existing function call ambiguous, this fact isn't detected by the incremental compiler and compilation erroneously succeeds when it should be failing. After a `clean`, compilation fails like it should.

I originally reported this as an [sbt bug](https://github.com/sbt/sbt/issues/7357), but I have since reproduced it with mill, so I'm going to assume that it's a zinc bug.

```
mkdir project
echo 'sbt.version=1.9.3' > project/build.properties
echo 'scalaVersion := "3.3.0"' > build.sbt

cat > A.scala << EOF
trait Foo
trait Bar

def foo(f: Foo) = ()
def qux = foo(new Foo with Bar {})
// this call is fine for now, but will be ambiguous once another overload is added
EOF
sbt compile
cat > B.scala << EOF
def foo(b: Bar) = () // add another overload, compilation should now fail
EOF
sbt compile # this succeeds, but shouldn't
sbt clean
sbt compile # now it fails, correctly
```

**Comment by eed3si9n** [comment]
Thanks for the report. Scala 3 maintains their own compiler bridge, which is typically the cause for Scala-specific issues. Could you report the issue here please? - https://github.com/lampepfl/dotty/labels/area%3Aincremental-compilation

**Comment by SethTisue** [comment]
This is a very easy mistake for bug reporters to make — all too easy!

~I've updated the repo description here to explicitly say "Scala 2".~ reverted

I've also submitted https://github.com/sbt/zinc/pull/1240 which updates the bug template and the readme to be clear about this.

**Comment by mberndt123** [comment]
Thanks for pointing me to the right repo @eed3si9n
