### ISSUE TITLE
Need some replacement for custom ClassfileManager

### ISSUE THREAD

**Issue by sjrd** [sbt/zinc#125]
In sbt 0.13, `IncOptions` has a field `newClassfileManager` of type `ClassfileManager`, which is configurable. In 1.0.0-M4, we only have a very limited `classfileManagerType`.

Scala.js uses the highly configurable `ClassfileManager` here: https://github.com/scala-js/scala-js/blob/v0.6.9/sbt-plugin/src/main/scala/scala/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L110-L137
This is necessary so `.sjsir` files are deleted when their "companion" `.class` files are deleted. Which of course is necessary for incremental compilation to work at all with Scala.js.

We absolutely need a way to implement the same functionality, i.e., this is a **blocker** for Scala.js. Whether by reintroducing `newClassfileManager` or another way to do it.

**Comment by stuhood** [comment]
Correspondingly, when pants uses zinc to build with scala.js, we have the same concern.

**Comment by stuhood** [comment]
@sjrd : One alternative here might be to lean further in on the virtual-file-system approach that @peiyuwang began with #181 . In particular, using a similar vfs implementation for scalac (assuming `scala.js` uses the scalac filesystem APIs) would capture these naturally.

**Comment by jvican** [comment]
@sjrd It seems we can already do this, but we need to dive deeper into the new Zinc 1.0 API. AFAIK, Grzgorz introduced a new interface called `ExternalHooks` that allows you to inject your own `LookUp` and `ClassFileManager` instances for further customisation.
  
This is how I would replicate that functionality with the new API:
```scala
import xsbti.compile.{IncOptions, ExternalHooks, ClassFileManager}

/** Patches the IncOptions so that .sjsir files are pruned as needed.
 *
 *  This complicated logic patches the ClassfileManager factory of the given
 *  IncOptions with one that is aware of .sjsir files emitted by the Scala.js
 *  compiler. This makes sure that, when a .class file must be deleted, the
 *  corresponding .sjsir file are also deleted.
 */
def scalaJSPatchIncOptions(incOptions: IncOptions): IncOptions = {
  // We can be more fine-grained and check which ClassFileManagerType we expect
  val inheritedNewClassfileManager =
    sbt.internal.inc.ClassfileManager.getClassfileManager(incOptions)
  val newClassfileManager = () => new ClassFileManager {
    private[this] val inherited = inheritedNewClassfileManager()

    def delete(classes: Iterable[java.io.File]): Unit = {
      inherited.delete(classes flatMap { classFile =>
        val scalaJSFiles = if (classFile.getPath endsWith ".class") {
          val f = FileVirtualFile.withExtension(classFile, ".class", ".sjsir")
          if (f.exists) List(f)
          else Nil
        } else Nil
        classFile :: scalaJSFiles
      })
    }

    def generated(classes: Iterable[java.io.File]): Unit = inherited.generated(classes)
    def complete(success: Boolean): Unit = inherited.complete(success)
  }
  // Use new external hooks interface to inject Scalajs ClassFileManager
  val hooks = new ExternalHooks {
    override def externalClassFileManager() = newClassfileManager
    override def externalLookup() = null
  }
  incOptions.withExternalHooks(hooks)
}
```
  
Does this sound reasonable to you?

**Comment by sjrd** [comment]
Does this compose with other transformations of `IncOptions` that also have their own `withExternalHooks`?

Also, this uses `sbt.internal.*`, so it could be a viable option only if the functionality being used is made publicly available outside of `sbt.internal`. Indeed, `internal` packages are not guaranteed to be supported, e.g., they could break binary compatibility at any time.

**Comment by jvican** [comment]
Can you write a code snippet that illustrates the motivation for the composition you're talking about? I'm not sure I'm following you there.
  
Regarding the stability of the API, granted. I agree that the API should have a method to get the `ClassFileManager` directly without going through that Scala object living in the internals of Zinc. I'll see what I can do about that and get back to you when I have a solution.

**Comment by sjrd** [comment]
> Can you write a code snippet that illustrates the motivation for the composition you're talking about? I'm not sure I'm following you there.

Consider another sbt plugin, written by someone else, that also needs to alter `incOptions` with its own `ExternalHooks`. Can the custom external hooks of both plugins compose? In terms of code snippet, just imagine a second copy of the same snippet you showed me, using `.foo` instead of `.sjsir`. Then the `incOptions` resulting from composing the two functions should delete both `.foo` and `.sjsir` files.

**Comment by dwijnand** [comment]
Is `xsbti._` public API does anyone know? What about `xsbti.compile._`?

**Comment by jvican** [comment]
Both of them are public @dwijnand.
  
@sjrd I'll look into the composability of `ExternalHooks`, but off the top of my head you can compose `ExternalHooks` by using inheritance and checking if there's already an external class file manager defined. That's the same approach you are using currently, as far as I see.

**Comment by dwijnand** [comment]
@jvican 
> Both of them are public @dwijnand

We should either state that explicitly or tweak http://www.scala-sbt.org/0.13/docs/Coding-Guideline.html#Hide+implementation+details to explicitly state that every other package that sbt provides is public API.

**Comment by smarter** [comment]
@jvican:
> I'll look into the composability of ExternalHooks, but off the top of my head you can compose ExternalHooks by using inheritance and checking if there's already an external class file manager defined. That's the same approach you are using currently, as far as I see.

This is really complicated to get right because you need to take into account the internal ClassFileManager as well as whether or not there already is an external ClassFileManager, and then I guess you need to make your own WrappedClassFileManager when overriding `externalClassFileManager` if there already is an external ClassFileManager ? This is twice as hard to get right as the previous API, which was already impossible to get right by yourself. I think this needs to be properly redesigned.

**Comment by smarter** [comment]
Actually `WrappedClassFileManager` is private in sbt so it's even worse than that: to properly override the external classfilemanager, you need to reimplement `WrappedClassFileManager`.

**Comment by jvican** [comment]
@smarter thanks for the feedback. Can you please open a new issue with that information and tje ideal API you'd like to see?

**Comment by smarter** [comment]
I have no idea what the ideal API would be.

**Comment by smarter** [comment]
Opened https://github.com/sbt/zinc/issues/312
