### ISSUE TITLE
Java wildcard import collision

### ISSUE THREAD

**Issue by aelgn** [sbt/zinc#1262]
## steps
`sbt 1.9.6`
`scala 3.3.1`

Given two packages both containing a java class A.
`a.b.c.A`
`x.y.z.A`

Create Sad.java:
```
import a.b.c.A;
import a.b.c.*;
import x.y.z.*;
public class Sad {
   public static f(A a) {
   }
}
```

Create main.scala:
```
@main
def main(): Unit = {
  Sad.f(null);
}
```

Incremental compile fails with [E049] Reference Error:
```
Reference to A is ambiguous.
It is both imported by import a.b.c._
and imported subsequently by import x.y.z._
```

## problem

Sad.java is correct since it explicitly imports `a.b.c.A`. This import statement makes the assertion that "Reference to A is ambiguous." incorrect.

## expectation

Zinc should be able to tell which A to import.

**Comment by eed3si9n** [comment]
You said

> Incremental compile fails with [E049] Reference Error

but the reproduction step doesn't seem to indicate any incremental compilation, like compile something, change the code, and compile again. If this also happens under clean compilation, I'd suspect this is actually Scala 3 compiler issue.
If you agree, could you report this to https://github.com/lampepfl/dotty/issues instead plz?

**Comment by aelgn** [comment]
I agree. There is even an issue for this bug in dotty already: https://github.com/lampepfl/dotty/issues/18529
