### ISSUE TITLE
"Found names used at the top level but no class" error

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#135]
## steps

Compile a source with just package name:

``` scala
package foo
```
## problem

Error "Found names used at the top level but no class..."
## expectation

We should display a warning, but not an error.

**Comment by romanowski** [comment]
I think we are doing  it now
https://github.com/sbt/zinc/blob/1.0/internal/compiler-bridge/src/main/scala/xsbt/ExtractUsedNames.scala#L58-L62

Maybe fatal warnings was on?

IMO if fatal warnings is on we should report this as info not as warning (TBH in our private build of zinc we downgrade this messages to infos anyway).

**Comment by eed3si9n** [comment]
Probably it was fatal warning.

**Comment by jvican** [comment]
Indeed, I confirm we're doing it with a warning. Closing optimistically, feel free to reopen if fatal warning was not the problem @eed3si9n.

**Comment by eed3si9n** [comment]
I think part of the problem is that the user might not be sure what why it's a problem and what they should do.
The warning comes from an interesting limitation of class-based name hashing, which requires at least one class-like thing on a source to make an entry. I think the implication is that if you change the file to: 

```scala
package foo

import something_bogus // expects an error, but it doesn't
```

The above import statement doesn't get caught by the incremental compiler, but the full compiler would catch it something like that.

Potential fix might be to reduce to "info" level, or tell user what to do.
