### ISSUE TITLE
ZipCentralDir.java references java.util.zip.ZipError

### ISSUE THREAD

**Issue by eirbjo** [sbt/zinc#1385]
## problem

The class  java.util.zip.ZipError has been unused in OpenJDK since JDK 9. Efforts are underway to mark this class as deprecated with the intention to eventually remove it in a future release.

This deprecation issue is being tracked here: https://bugs.openjdk.org/browse/JDK-8336843

To help minimize ecosystem impact, I'm reaching out to SBT because we identified that the `ZipCentralDir.java
` file throws ZipError.

If the deprecation suggestion is accepted by OpenJDK in a future release, then this reference will cause a compiler warning. In a later release, the removal of the class will cause a compilation error.

Looking at the SBT code, it seems it would be more appropriate to throw `java.util.zip.ZipException` in these cases.

This issue is mostly a heads-up. If you want to take action now and remove/rewrite the referencing code, that would be great. Otherwise, you might start seeing compiler warnings about the deprecation in a not-so-far future..

Thanks!

**Comment by eed3si9n** [comment]
@eirbjo Thanks!

**Comment by eed3si9n** [comment]
I have two PRs for 1.x and 2.x:
- https://github.com/sbt/zinc/pull/1391
- https://github.com/sbt/zinc/pull/1393

**Comment by eirbjo** [comment]
Thanks for takkng care of this @eed3si9n . I noticed that `ZipCentralDir.java` now has an unused import for `java.util.zip.ZipError`. This should probably be removed as well.

**Comment by eed3si9n** [comment]
Doh!
