### ISSUE TITLE
Sources for generated types are not included in source artifacts

### ISSUE THREAD

**Issue by kiritsuku** [sbt/zinc#140]
`compiler-interface-1.0.0-M5-sources.jar` doesn't include sources for `xsbti.compile.Compilers` or `xsbti.compile.IncOptions` because their sources are generated by sbt-datatype. It would be nice if the generated Java sources were actually part of the source artifact.

**Comment by jvican** [comment]
Do you know something about this @eed3si9n ? It would be indeed good because this would mean that people can have a look at all the generated sources, which include an extensive part of the Zinc Java API.

**Comment by dwijnand** [comment]
This is due to https://github.com/sbt/sbt/issues/2205.

See my workaround in https://github.com/sbt/librarymanagement/pull/62.

**Comment by Friendseeker** [comment]
Fixed upstream
