### ISSUE TITLE
Documentation request - how to use a custom built zinc with sbt or other build tools?

### ISSUE THREAD

**Issue by OndrejSpanel** [sbt/zinc#1428]
I am thinking about contributing to zinc, I would like to get my hand dirty and attempt to fix some issues I encounter. I have read the documentation, esp. https://github.com/sbt/zinc/blob/1.10.x/CONTRIBUTING.md, and there is one thing which seems basic to me, yet I do not see it: when I build my own version of zinc, how should I start sbt or other build tool so that it uses it?

To test zinc do you also build sbt? Or do you somehow place the new zinc on a sbt classpath, or how is this done?

**Comment by Friendseeker** [comment]
Your contribution would be very welcomed! Zinc has a contributor shortage and years old ticket unsolved. Any contribution would be a great step forward.

For how to let sbt to use custom zinc version, c.c. https://github.com/sbt/zinc/issues/1234#issuecomment-1834475788. The setup also works for active debugging a custom zinc build used by sbt.

**Comment by eed3si9n** [comment]
If you check out both sbt and zinc in `$HOME/work`, and from `$HOME/work/sbt/` run the following:

```bash
sbt -Dsbtzinc.path=../zinc
```

it should be able to build both Zinc and sbt together. Then you can run

```
> publishLocalBin
```

to publish, and from a test project:


```
> reboot dev
```

to wipe out the boot directory and re-resolve to a SNAPSHOT version of sbt and Zinc.
