### ISSUE TITLE
Failure to analyze a Java class causes analysis to be lost

### ISSUE THREAD

**Issue by stuhood** [sbt/zinc#144]
With or without a `ClassfileManager` in place, failing to analyze javac compilation in [AnalyzingJavaCompiler](https://github.com/sbt/zinc/blob/2541fa40f245c612f5ad8d363b0ffea6dbffa991/zinc/src/main/scala/sbt/internal/inc/javac/AnalyzingJavaCompiler.scala#L91) causes classfiles to be created which are not tracked in the analysis, and thus won't be removed.

**Comment by stuhood** [comment]
More discussion on #94.

**Comment by stuhood** [comment]
In discussions with @eed3si9n (and previously with @gkossakowski on #94), it sounds like using the VFS support from http://docs.oracle.com/javase/8/docs/api/javax/tools/JavaCompiler.html to address this transactionally would be reasonable. Will mail sbt-dev@ to confirm.

**Comment by stuhood** [comment]
Discussion here: https://groups.google.com/d/topic/sbt-dev/j4uFWvRW-OA/discussion

**Comment by stuhood** [comment]
. @peiyuwang pointed out that it is trivial to reproduce the "lost analysis" case by just... removing the analysis file for a java module. Because AnalyzingJavaCompiler diffs classfiles on disk before/after (rather than recording what javac has said it (re)created), no classfiles will be recorded as new, and no analysis will be created.

**Comment by peiyuwang** [comment]
#181 implements the VFS idea proposed earlier for javac.

**Comment by stuhood** [comment]
Merged as 47db3df0c6914d4a479917f38f07eee1e48e61ec
