### ISSUE TITLE
InvalidationProfiler sometimes doesn't register cycles

### ISSUE THREAD

**Issue by ephemerist** [sbt/zinc#1512]
## steps

Trigger a compilation on a compilation unit with scala sources and pipelining disabled, with an InvalidationProfiler as part of IncOptions.externalHooks. 

## problem

InvalidationProfiler.registerRun is called, but the run has no cycles.

## expectation

The run should have at least one cycle (or more, depending on what was invalidated).

## notes

Fixed in #1511.

The problem was created on the 1.10.x branch by #1312, which meant that `mergeAndInvalidate` (and hence `registerCycle`) is no longer called for non-pipelined builds from `dependencyPhaseCompleted`. The bug can be seen by running the new scripted test `check-cycles-no-pipelining` without the zinc-core code changes in #1511.

**Comment by ephemerist** [comment]
@eed3si9n thanks for the merge. What's the process to get 1.10.6 out with this change?

**Comment by eed3si9n** [comment]
I typically publish Zinc when I release sbt 1.x, currently every 1 ~ 2 weeks.

**Comment by Friendseeker** [comment]
I guess dancing on a landmine in #1312 can blow things up. `InvalidationProfiler` becomes the collateral damage.

Thanks for the investigation!
