### ISSUE TITLE
Port the test for warning on transitive macro recompilation, with opt-out

### ISSUE THREAD

**Issue by dwijnand** [sbt/zinc#154]
See https://github.com/sbt/sbt/pull/2659. I failed to figure out how to do so in https://github.com/sbt/zinc/pull/143.

**Comment by jvican** [comment]
This would involve augmenting our test infrastructure to:
  
1. Check that warnings/logs have been emitted by Zinc.
2. Supporting tests that have macros (adding option to add the paradise compiler plugin and scala-reflect in the classpath, or whatever it's required nowadays to compile macros). I recommend to study how sbt handles it.
  
If I don't miss something, with these two options one should be able to port this test.
