### ISSUE TITLE
AnalyzingJavaCompiler.compile is inconsistent if it accepts MultipleOutput

### ISSUE THREAD

**Issue by kiritsuku** [sbt/zinc#163]
The `compile` method is doing two checks on the `output` argument. First it handles both possible values of `Output` here: https://github.com/sbt/zinc/blob/2541fa40f245c612f5ad8d363b0ffea6dbffa991/zinc/src/main/scala/sbt/internal/inc/javac/AnalyzingJavaCompiler.scala#L50-L54

But then it calls `commandArguments` here: https://github.com/sbt/zinc/blob/2541fa40f245c612f5ad8d363b0ffea6dbffa991/zinc/src/main/scala/sbt/internal/inc/javac/AnalyzingJavaCompiler.scala#L69 This method internally throws an exception in case output is `MultipleOutput`.

Obviously it is not possible to pass a `MultipleOutput` right now. One of the two tests is wrong but which one?

I haven't figured out yet if just passing a `SingleOutput` would do the right now. I'm going to try it out. We don't have multiple output directories anyway, therefore I think `MultipleOutput` contains only one entry.

**Comment by kiritsuku** [comment]
Using `SingleOutput` may not be possible because scalac accepts multiple output directories and `MixedAnalyzingCompiler.compile` uses the same output for both scalac and javac.

See here for scalac: https://github.com/sbt/zinc/blob/2541fa40f245c612f5ad8d363b0ffea6dbffa991/zinc/src/main/scala/sbt/internal/inc/MixedAnalyzingCompiler.scala#L48
And here for javac: https://github.com/sbt/zinc/blob/2541fa40f245c612f5ad8d363b0ffea6dbffa991/zinc/src/main/scala/sbt/internal/inc/MixedAnalyzingCompiler.scala#L56

**Comment by kiritsuku** [comment]
I also want to point out that this was not a problem is sbt. I guess there is a behavior change somewhere.

**Comment by kiritsuku** [comment]
I think I found out why this problems happens. The bug is introduced here: https://github.com/sbt/zinc/commit/2541fa40f24

Originally (at this location: https://github.com/sbt/zinc/commit/2541fa40f24#diff-cae836220f2f0b797e451fe635860c03L68) javac was called directly. Eclipse provided its own implementation for javac (because Eclipse ships with its own Java compiler, called ECJ). The new implementation however, first calls `JavaCompiler.commandArguments`, which is an implementation for javac and therefore not suitable for ECJ. Only in the line subsequent line there is a dispatch to the correct implementation.

@eed3si9n What would you suggest how should this be fixed? ECJ never uses the `args`, therefore they definitely shouldn't be created at this location. I would move the creation inside of the `run` method or inside of a closure that is passed to `run` in order to minimize the number of arguments that are passed to `run`.

**Comment by eed3si9n** [comment]
Is the problematic line here?:

``` diff
+      val target = output match {
+        case so: SingleOutput   => so.outputDirectory
+        case mo: MultipleOutput => throw new RuntimeException("Javac doesn't support multiple output directories")
+      }
```

If we put some dummy value when we find `MultipleOutput` would that work for you?

**Comment by kiritsuku** [comment]
Yes, if it wouldn't throw an exception our implementation would work fine.

**Comment by kiritsuku** [comment]
@eed3si9n Do you think you have the time to look into that soon?

**Comment by eed3si9n** [comment]
Yea. I'll get it done today.

**Comment by kiritsuku** [comment]
It's so cool. I already tested the change and it works well. Thanks!
