### ISSUE TITLE
Make FileBasedStore.set safer

### ISSUE THREAD

**Issue by peiyuwang** [sbt/zinc#178]
We currently wraps around `FileBasedStore` that underlying update a temp file first and rename only upon successful writes so the original analysis file is not corrupted in case update fails.

Would be nice to upstream this wrapper [1].

[1] https://github.com/pantsbuild/pants/pull/3886/files#diff-297b1b6a94d202511b784fd43284b6ebR119

**Comment by dwijnand** [comment]
Fixed in #231. Thank you @peiyuwang for the fix, and @jvican for the PR.
