### ISSUE TITLE
Publish zinc for 2.12

### ISSUE THREAD

**Issue by kiritsuku** [sbt/zinc#194]
Right now it is only published for 2.10 and 2.11. 2.12 needs to be supported too.

**Comment by ghost** [comment]
+1 need 2.12 too

**Comment by jvican** [comment]
Hi @sschaef and @ghost, we'll be cutting a version towards the end of this week. Thanks for showing interest!

**Comment by jvican** [comment]
2.12 release is [out](http://search.maven.org/#search|ga|1|a:"zinc_2.12").
