### ISSUE TITLE
Replace sbinary with sjson-new

### ISSUE THREAD

**Issue by dwijnand** [sbt/zinc#203]

**Comment by jvican** [comment]
Is this going to happen any time soon? Could you have a stab at it @dwijnand?

**Comment by dwijnand** [comment]
A good portion of this was done when moving to contraband, but I'd like to keep this open to completely remove sbinary. It's probably going to happen sometime before we cut sbt 1.0.0.

**Comment by jvican** [comment]
Could you elaborate on what's missing here? If this is something that can be done quickly and I have enough cycles for it, I may do it during this week. If it's something that requires expertise that you only guys know, I prefer to leave it to you and I don't mind waiting.

**Comment by dwijnand** [comment]
Sorry, I'm not sure what's necessary until I do it.

The only requirement is that sbinary isn't a transitive dependency of sbt 1.

The reason is that we don't want 3 different systems for serialisation (sbinary, pickling and sjson-new/scala-json-ast). For now this is removing sbinary. Possibly in the future we should finish removing/replacing pickling too.

**Comment by jvican** [comment]
Thanks for elaborating @dwijnand. I'll leave it up to you | @eed3si9n, we'll need to do this before a stable release of Zinc.

**Comment by jvican** [comment]
@eed3si9n I'd like to include this for the Scala Center hackathon taking place at Scalasphere. Could you please elaborate on what's required in this ticket? A few links to relevant files would be very helpful.

**Comment by eed3si9n** [comment]
Traditionally sbt 0.13 used sbinary for serializing datatypes. TextAnalysisFormat in Zinc, caching etc uses the codec for sbinary. For new Zinc and sbt 1, we are switching to use sjson-new for serializing the datatypes. The way we should tackle it is by using Contraband to let both the datatype and sjson-new codecs generate from the schema.

- http://www.scala-sbt.org/contraband/
- https://github.com/sbt/zinc/blob/1.0/internal/zinc-persist/src/main/scala/sbt/internal/inc/TextAnalysisFormat.scala

**Comment by jvican** [comment]
Fixed in #351, with protobuf instead of sjson-new.
