### ISSUE TITLE
Incremental compilation results and absolute paths

### ISSUE THREAD

**Issue by gabro** [sbt/zinc#214]
I just found out that the paths in  `streams/compile/incCompileSetup/\$global/streams/inc_compile_2.11` are absolute.

Is this a deliberate design choice? If yes what are the tradeoffs?
I'm facing [this issue](http://stackoverflow.com/questions/41891700/preserve-results-of-sbt-incremental-compilation-when-moving-project-directory) where I need to change the absolute path of the project (the real use case is for a CI pipeline) and I want to re-use the compiled classes.

Is there a way of doing this (other than, well, using `sed` to update the paths)?

**Comment by eed3si9n** [comment]
Thus far it's been the design decision to use absolute paths everywhere.
We might change that since there's a PR to enable caching.

**Comment by eed3si9n** [comment]
I'm closing this in favor of https://github.com/sbt/zinc/issues/218

**Comment by gabro** [comment]
Thanks for the reply, looking forward to #218
