### ISSUE TITLE
Is antStyle still needed?

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#22]
sbt 0.13's IncOptions has an option called [`antStyle`](https://github.com/sbt/sbt/blob/0.13.9/compile/inc/src/main/scala/sbt/inc/IncOptions.scala#L69-L83)

``` scala
    /**
     * THE `antStyle` OPTION IS UNSUPPORTED, MAY GO AWAY AT ANY POINT.
     *
     * Enables "ant-style" mode of incremental compilation. This mode emulates what Ant's scalac command does.
     * The idea is to recompile just changed source files and not perform any invalidation of dependencies. This
     * is a very naive mode of incremental compilation that very often leads to broken binaries.
     *
     * The Ant-style mode has been introduced because Scala team needs it for migration of Scala compiler to sbt.
     * The name hashing algorithm doesn't work well with Scala compiler sources due to deep inheritance chains.
     * There's a plan to refactor compiler's code to use more composition instead of inheritance.
     *
     * Once Scala compiler sources are refactored to work well with name hashing algorithm this option will be
     * deleted immediately.
     */
    val antStyle: Boolean) extends Product with Serializable {
```

Is this still needed? /cc @SethTisue

**Comment by SethTisue** [comment]
It seems very likely it's not needed anymore. There aren't any references to `incOptions` or `antStyle` in the scala repo, either in the current contents or in the history, either. And there aren't any mentions of this in https://github.com/scala/scala-dev/issues/45 or https://github.com/gkossakowski/scala/pull/2 or https://github.com/scala/scala/pull/4455.

@lrytz @retronym @adriaanm any memories of this? It's @gkossakowski's, from May 2014.

**Comment by retronym** [comment]
It was added as a defensive measure so that the SBT build would be at least no worse than Ant wrt recompilation. When working on changes that are pathological for the normal inc compiler mode, one could switch in to this mode and use our old tricks of touching files we know need recompilation. 

It was intended to be added to a developer local .sbt file, rather than in the official build.

**Comment by eed3si9n** [comment]
@retronym Thanks for the input. We'll keep it around then.

**Comment by SethTisue** [comment]
I'll find somewhere to document this.
