### ISSUE TITLE
Zinc has inconsistent names: ClassfileManager vs ClassFileManager

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#230]
It seems that https://github.com/sbt/zinc/commit/47db3df0c6914d4a479917f38f07eee1e48e61ec introduced a name change in `ClassfileManager`, turning it into `ClassFileManager`. This change is inconsistent with the object living in `sbt.internal.inc` that is named `ClassfileManager`.
  
For consistency reasons, we should stick with one style. It seems the whole new Java API is written in the capital letters style, so I slightly lean towards renaming the object `ClassfileManager` to `ClassFileManager`. However, I wonder if this change is worth it because IDEs and key Scala projects like Scala.js need to keep track of these changes. Yes, we've already changed a lot the API, another change doesn't matter. But yet, I'd like to start a discussion on this because it's not clear to me where we should care about users and where we shouldn't. This affects current build tools like Pants (/cc @stuhood @peiyuwang), Bazel, sbt (@dwijnand, @eed3si9n), and the aforementioned Scalajs (@sjrd, perhaps also Scala Native? /cc @densh).

**Comment by jvican** [comment]
Related patch https://github.com/sbt/zinc/commit/47db3df0c6914d4a479917f38f07eee1e48e61ec aside from https://github.com/sbt/zinc/commit/47db3df0c6914d4a479917f38f07eee1e48e61ec.

**Comment by romanowski** [comment]
+1

It used to be `ClassfileManager` but was recently changed (in some places) to `ClassFileManager`.

**Comment by peiyuwang** [comment]
Also +1 for unifying naming. 

fwiw, inconsistency already exists before 47db3df0c6914d4a479917f38f07eee1e48e61ec. So when `ExternalHooks.ClassFileManager` is merged with trait `ClassfileManager` I sticked to the Java naming. I probably should have called out the in the PR, my appologies.

FYI, in case API changes are unavoidable, Pants has a [deprecation process](http://www.pantsbuild.org/deprecation_policy.htm) that works for us so far.

**Comment by jvican** [comment]
@peiyuwang Indeed, that change was introduced before, when the Java API was designed with contraband. Sorry for the misunderstanding.
  
I don't know how malleable is the new Zinc API in terms of binary compatibility. My understanding is that we msut have a binary compatible API that we can maintain over two years (at the very least).
  
I'm not sure if marking `ClassfileManager` as deprecated would be useful in this case. We already have too many binary incompatible errors, and deprecations are more useful when applied to stable APIs. If we add a deprecation for this, perhaps we'll end up confusing people.

**Comment by jvican** [comment]
This is a hackathon ticket for anyone interested in improving the Zinc API. The changes required for this should go to this file: https://github.com/sbt/zinc/blob/1.0/internal/zinc-core/src/main/scala/sbt/internal/inc/ClassfileManager.scala. I propose that the class is renamed as `ClassFileManager` and that this change is added to the MIGRATION.md file so that users of the API are notified of it at release time.

**Comment by jvican** [comment]
This was fixed by #252. The same change has happened to ClassfileManagerType, that is now `ClassFileManagerType`.
