### ISSUE TITLE
Zinc is not handling mixed compile order

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#234]
See https://github.com/sbt/zinc/blob/1.0/zinc/src/main/scala/sbt/internal/inc/MixedAnalyzingCompiler.scala#L70.
  
`MixedAnalyzingCompiler` is not handling mixed compile order (thought: maybe because it's not really necessary? if scalac gets java sources, it will spawn a java compiler on its own).
  
A follow-up on this ticket should address whether this is necessary and if so make a PR to fix it. This is not high-priority so it can stay for a while without us worrying too much about this.

**Comment by smarter** [comment]
> if scalac gets java sources, it will spawn a java compiler on its own

I don't think so, it should only parse the java sources and enter symbols in the compiler scope.

**Comment by jvican** [comment]
Is this the current behaviour? Are you talking about parsing java class files or java sources? How can you enter symbols in the compiler scope without the full knowledge of the compiled class files? In my understanding, scalac has to compile java sources to get class files, and then parse them to create symbols. Is this correct?

**Comment by smarter** [comment]
No, scalac has its own Java parser, so that it doesn't have to rely on javac for anything: https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/javac/JavaParsers.scala

**Comment by jvican** [comment]
Okay, got it, so that's basically lifting Java sources to Scala trees. Thanks for the info, that was useful.

**Comment by dwijnand** [comment]
The TODO doesn't imply that "Zinc is not handling mixed compile order".

Mixed is the default compilerOrder, so there's no way it's "not handled".

> A follow-up on this ticket should address whether this is necessary and if so make a PR to fix it. This is not high-priority so it can stay for a while without us worrying too much about this.

If you happen to be in MixedAnalyzingCompiler.scala could you kill that TODO please?

I'm closing this.

**Comment by jvican** [comment]
What I tried to describe --and I failed-- is that mixed may be handled differently than it is. Right now, `ScalaThenJava` has the same behaviour in the `MixedAnalyzingCompiler` as `Mixed`.
  
What I tried to ask is: should we have another strategy for `Mixed`? Is this possible?
  
I'm not sure we should kill this TODO. Perhaps we should define first what mixed means.

**Comment by dwijnand** [comment]
Mixed has come to mean ScalaThenJava: https://github.com/scala/scala/pull/5661/commits/27c10db549e6f43571663d0162b58fc04fbb34bf

We should do something about making this clear, or even better obvious.

**Comment by jvican** [comment]
Great, this is what this ticket was partially about: making the situation clear.

**Comment by dwijnand** [comment]
I dislike repurposing issues. Issues are free, and renaming GitHub issues has unfortunate side-effects like breaking threading in Gmail/Google Inbox so I try and avoid it.

Created #235 to make the situation clear.
