### ISSUE TITLE
Name hashing does not register names of synthetic symbols

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#238]
Ported from https://github.com/sbt/sbt/issues/2537.
  
The following example does not work:
```scala
// A.scala
case class A(a: Int)
// private object A

// B.scala
object B {
  A(1)
}
```
  
When we incrementally compile and uncomment `private object A`, Zinc does not recompile `B.scala` which should fail. Before the explicit creation of object A, Scala was synthesizing a companion object with an `apply` method, and that's why B.scala can use `A(1)` which is translated to `A.apply(1)`. However, Scala does not synthesize new members if they already exist in scope, so the consumer code is not valid anymore.

**Comment by jvican** [comment]
Related (but already fixed, check `naha-synthetic`): https://github.com/gkossakowski/sbt/issues/9.

**Comment by romanowski** [comment]
@jvican are you sure it should not compile? I tested this using scala 2.11.8 and:
- zinc recompiled B when I add `private object A`
- clean compilation reports no problems when I have `private object A` added

**Comment by jvican** [comment]
I got that example from https://github.com/sbt/sbt/issues/2537, and assumed that should not compile based on @smarter's comments. However it compiles with latest Scala, so I'm closing this since this is not an issue of the incremental compiler.
