### ISSUE TITLE
Add sbt plugin to compile with Zinc 1.0

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#241]
I'm writing a sbt plugin to compile sbt projects living in 0.13.13 with Zinc 1.0 via isolated classloaders. I will report on my progress here and add more details to this issue.
  
I think that if I get this right this will be a game changer for the Scala community, since Scala devs will be able to try Zinc versions independently of the sbt version they use.

**Comment by romanowski** [comment]
Great to hear that! I would love to support cached compilation in zinc 1.0 - so once you have anything ready I will see I can can plug in somewhere with Hoarder.

**Comment by jvican** [comment]
The sbt plugin has been implemented in the sbt-plugin branch of the Scala Center fork of Zinc. Have a look at the docs: https://github.com/scalacenter/zinc/blob/sbt-plugin/README.md.

I'm happy to merge this upstream. Let me know if you want this to be PR'd @eed3si9n.

**Comment by jvican** [comment]
Given how close we're from sbt 1.0, I proceed to close this.
