### ISSUE TITLE
Allow users to provide librarymanagement update configuration

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#308]
Ref https://github.com/sbt/zinc/pull/307
Ref https://github.com/sbt/zinc/issues/310

Zinc internally uses library management module to grab compiler bridge module, but ideally it should accept an instance of lm during initialization, so configuration is opaque to Zinc.

**Comment by Friendseeker** [comment]
https://github.com/sbt/zinc/blob/03d0c7fc4d3b901f426fb01038448c68d2a9a31c/zinc/src/main/scala/sbt/internal/inc/ZincUtil.scala#L42-L50

Looks like Zinc user now directly provides a complier bridge jar now.
