### ISSUE TITLE
Rename any use of the term "Pimp" to "Enrich"

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#309]
There's been a number of discussion on Twitter about how horrible the choice of term "Pimp" was to the impression of Scala:

- https://twitter.com/coda/status/93003343965851648
- https://twitter.com/coda/status/93049114106920961

> Refactored: plz don't use the "pimp" metaphor; it has unintended connotations which have offended and alienated potential Scala programmers.

The standard replacement is "Enrich", "Enrichment", or "RichX".
I sometimes call them "method injection" or "static monkey patching", but never pimp.

**Comment by jvican** [comment]
I've never stopped to think about what pimp actually means. So I'm in for this change 👍 Good idea.
