### ISSUE TITLE
Contraband generated code not very forwards compatible

### ISSUE THREAD

**Issue by stuhood** [sbt/zinc#317]
contraband in zinc is configured to generate Java code with direct access to an N-arg constructor as the only mode of creating an object. This will make it very difficult to add/remove parameters later, as they cannot be individually deprecated, and adding a new parameter would require a new overloaded constructor (which gets confusing quickly).

@eed3si9n pointed to https://github.com/sbt/sbt/blob/1.0.x/run/src/main/contraband-scala/sbt/ForkOptions.scala as an example of exposing a Zero-arg constructor, and then using the Builder pattern instead. But it's possible that contraband should support generating Builders by default, so that you can differentiate between a partially constructed object with missing required fields, and a fully constructed object that is known to satisfy the constraints on which fields are required.

**Comment by jvican** [comment]
Thanks for reporting @stuhood. From my point of view, this requires a change in the contraband sources, so anyone tackling this issue is invited to make a PR over there.

**Comment by stuhood** [comment]
It's no one's fault but my own, but I just spent about a day digging into why no incremental compile was happening in this branch... before tracking it down to the following constructor call:
```
new xsbti.compile.IncOptions(
  transitiveStep,
  recompileAllFraction,
  relationsDebug,
  apiDebug,
  apiDiffContextSize,
  apiDumpDirectory.asJava,
  classfileManager(log).asJava,
  useZincFileManager,
  recompileOnMacroDef.map(java.lang.Boolean.valueOf).asJava,
  true, // nameHashing
  false, // storeApis: not actually used for incremental compile as of 1.0.0-X16.
  false, // antStyle
  Map.empty.asJava, // extra
  defaultIncOptions.logRecompileOnMacro,
  defaultIncOptions.externalHooks
)
```
...except that's not what those three booleans in the middle represent.

So yea... builder pattern for Java APIs is critical =(

**Comment by stuhood** [comment]
Have now ported that codepath to `IncOptionsUtil.defaultIncOptions` + the contraband generated builder methods.

**Comment by jvican** [comment]
Yes, `defaultIncOptions` is the way to go @stuhood. Glad you found it.
  
@eed3si9n Any possibility we can remove the classes constructors by passing a special option to Contraband?

**Comment by eed3si9n** [comment]
We might be able to make the constructor package private, and generate static factory method like `apply`.

**Comment by jvican** [comment]
> We might be able to make the constructor package private, and generate static factory method like apply.
  
If we don't do this now, we're doomed to keep this for the rest of 1.x. I don't think that's good...

**Comment by jvican** [comment]
Is there any reason why this was reopened? I don't remember well what happened, but it's my understanding that #362 fixes this issue.

**Comment by eed3si9n** [comment]
I reopened it when sbt/contraband#98 closed it automatically.
We now can close this.
