### ISSUE TITLE
Make `AnalysisMapper` public

### ISSUE THREAD

**Issue by stuhood** [sbt/zinc#320]
`AnalysisMapper` looks like the right way to [avoid needing to be aware of zinc analysis content](https://github.com/sbt/zinc/issues/218), but currently it is an `sbt.internal.inc` API.

**Comment by jvican** [comment]
The whole analysis mappers API is going to change drastically. It's highly tied to the serialization mechanism. The mechanism that I envision is more high-level operating only on the API classes and mapping from one class to the same class.
  
However, I must add that I'm working on making the content of analysis machine-independent. So this won't be necessary in theory. I'm just adding these hooks in case users need to perform more changes before serializing/deserializing.

**Comment by stuhood** [comment]
Yea, these seem challenging to use correctly... not clear yet which of the methods need overrides in order to catch all relevant cases. Our implementation currently looks like https://github.com/pantsbuild/pants/compare/master...twitter:stuhood/zinc-upgrade-2017-06#diff-297b1b6a94d202511b784fd43284b6ebR166 ... but I'm not able to (easily) test portability until after `X17` is available.

**Comment by romanowski** [comment]
@stuhood [Here](https://github.com/romanowski/hoarder/blob/master/0.13/hoarder/src/main/sbt_0.13/org.romanowski.hoarder/core/SbtAnalysisMapper.scala) is an example how this is done inside hoarder (code is ported to work with sbt 0.13.x but hopefully you will be able to get the main idea).

If you like I can try to explain what and how need to be mapped.

**Comment by stuhood** [comment]
@romanowski : Thanks. Looks similar.

https://github.com/sbt/zinc/pull/351 is relevant. I'm hoping that @jvican agrees that a `getMachineIndependentMapper` implementation that supports multiple bases to relativize to is worth including... it would be really great if both hoarder and pants could use the default implementation.

**Comment by jvican** [comment]
I'm happy to include such implementation. I'm just not sure how the interface should look like. If we want to make it generic, we'll need some assumptions that downstream users can agree on.
  
@stuhood Can you try to implement a rough prototype of `ReadMapper` and `WriteMapper` so that I get an idea of what you mean and we extrapolate a generic implementation from there?

**Comment by jvican** [comment]
@stuhood I had a shot at implementing generic read and write mappers. [This is the best I came up with](https://github.com/sbt/zinc/pull/351/commits/47a9c01f68cfd28633c40bd2a03dbe081ddea399). The mappers take `RootPaths` that define `sourcesRootPath`, `libariesRootPath` (for jars) and `productsRootPath` (for class files).
 
Can you let me know what you think about it?
  
/cc @romanowski who may use this as well in Hoarder.

**Comment by stuhood** [comment]
@jvican : That looks like it would work for our usecase: pants would use the same path for the `librariesRootPath` and `productsRootPath` because all 3rdparty jars are symlinked under a particular directory. It would be good to look concretely at what those values would be in an `sbt` build. Also, if it's possible to be more precise about the relationship between "library" and "external" and "binary" deps in analysis, that would be great (ex: `mapBinaryFile` relativizes to `librariesRootPath`, which is confusing).

The last bit that we have manipulated in the past has been the JDK's classpath entries: @romanowski used the bootstrap classpath of the current JVM to do that in the link he posted above, and pants has always rebased JAVA_HOME explicitly.

**Comment by jvican** [comment]
Yeah @stuhood, unfortunately JDK classpath entries must be special cased, unless the build tool sym links them from every project or use one of the tricks you mention. 
  
I agree that we should be clearer on the differences between "library" and "external" and "binary" deps in analysis.
  
This has been fixed in #351, so it can be closed.
