### ISSUE TITLE
Document how to clean only the analysis file of Zinc

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#337]
This is a ticket for the Scala Center spree happening at Scala Wave (Gdansk, Poland).
  
The [sbt docs](http://www.scala-sbt.org/0.13/docs/Running.html) do not document the fact that sbt allows you to remove the analysis file in Zinc, **without** forcing other tasks like dependency resolution to kick in.
  
Usually, what people do is to run `clean` in the root and that means that the next time they compile, dependencies will be resolved and checked, and other tasks that were before cached need to be executed.
  
However, what most of people don't know, and what the docs don't say, is that if you execute `compile / clean`, only the analysis file will be removed.
  
The goal of this ticket is to clearly document this in the sbt docs linked at the beginning of this ticket. The docs [are in the following repo](https://github.com/sbt/website). 
  
By doing this, you will help the community in two regards:
  
1. You will help to clear up a common source of confusion.
1. The documentation can make people's habits more efficient -- less resolution, more time to have coffee or code!
  
Contributing to docs is an important task for OSS projects, and it's really appreciated.

**Comment by jvican** [comment]
I did not follow up on this, but this is false:
  
> The sbt docs do not document the fact that sbt allows you to remove the analysis file in Zinc, without forcing other tasks like dependency resolution to kick in.
  
I opened https://github.com/sbt/sbt/issues/3542 so that someone can have a look at it. So I'm closing this because this will be something properly advertised in sbt/sbt if someone implements it and lands.

**Comment by dwijnand** [comment]
> So I'm closing this [..]

Closing. Tracked as https://github.com/sbt/sbt/issues/3542.
