### ISSUE TITLE
Port implicit higher kinded test to Zinc

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#339]
There is a test that hasn't been ported to Zinc, that is `implicit-higher-kinded`, and it's pending (that means it's not passing yet).
  
You can port it by applying [the following commit](https://github.com/sbt/sbt/commit/7cca5422c48ff50942f25fb9c82c9c063b08fe4b) on top of the latest master. The description of the issue in sbt/sbt is: https://github.com/sbt/sbt/issues/686.
  
The goal of this ticket is to make a PR with this new test.

**Comment by Krever** [comment]
It turned out that the test is passing, so should not be marked as pending.

**Comment by Duhemm** [comment]
Thanks @krever!

**Comment by jvican** [comment]
It looks like name-hashing solved this issue, which is great news! :smile:.

**Comment by jvican** [comment]
(opening so that it gets closed when @Duhemm  merges the PR)
