### ISSUE TITLE
Remove any trace of the resident compiler

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#340]
The resident compiler was a thing, some time ago, and the idea was abandoned because it was deemed to be hard. From Grzgorz's description of the upstream sbt issue:
```
Inspired by: http://stackoverflow.com/questions/23278316/experimental-support-for-keeping-the-scala-compiler-resident-with-sbt-resident-l

The conclusion from our experiments with resident compilation is that the feature is very difficult to implement (due to Scala compiler being not designed for that use case). The benefit of resident compilation turned out to be much smaller than anticipated.

For those reasons, we don't plan to work on resident compilation and we should remove any references from sbt to it.
```
  
The goal of this ticket is to grep for "resident" and resident compilation and remove any trace of it, both in the APIs and docs.
  
This is a ticket ported from sbt: https://github.com/sbt/sbt/issues/1287.

**Comment by jvican** [comment]
For the record, this is a blocker for RC since it affects the binary API.

**Comment by stuhood** [comment]
+1
