### ISSUE TITLE
The java compiler should always be run

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#343]
This is a port of https://github.com/sbt/sbt/issues/1178.
  
Compile mixed order runs first the scala compiler, using the java parser to read java symbols, and then executes the java compiler with the class files that have been generated by the scala compiler.
  
@dragos complained that Scala's Java parser is not 100% compatible and some tools do not report Java parser errors coming from the Scala compiler (like Scala IDE). Therefore, to get these errors in a reliable way, we always have to run the java compiler (from the jdk) even if scala fails. More details are in the original ticket.
  
The place to fix this issue is probably https://github.com/sbt/zinc/blob/d253375c3250eacb76864792d8047ede32ad5503/internal/zinc-core/src/main/scala/sbt/internal/inc/Compile.scala or the classes it calls. Tests can be added in the `zincCore` project.
  
As there are no error messages shown to the user, I'm labeling this as a bug.

**Comment by fommil** [comment]
Fyi ensime uses the jdk for Java code. We ignore everything about java from scalac.

**Comment by smarter** [comment]
> Therefore, to get these errors in a reliable way, we always have to run the java compiler (from the jdk) even if scala fails. More details are in the original ticket.

The issue with doing that is you may get spurious errors if Java code refers to Scala code and bytecode for the Scala code was not emitted because the Scala compilation failed. Seems like it'd make more sense to fix the tools that ignore messages from scalac.

**Comment by jvican** [comment]
> The issue with doing that is you may get spurious errors if Java code refers to Scala code and bytecode for the Scala code was not emitted because the Scala compilation failed. Seems like it'd make more sense to fix the tools that ignore messages from scalac.
  
But those "spurious" errors are not "spurious", they are legitimate. The Scala compiler, for whichever reason, has failed, and the errors evidence two things in a trustworthy way:
  
1. If the java sources depend on the Scala sources and the Java compiler fails, it means Scala sources haven't been compiled and hence the bug is there.
2. If the java sources do not depend on Scala code and Java compilation succeeds, users will realize that the culprit is the Scala compiler depending on Java code (because Java's compiler is the "single source of truth") and will correctly report the situation upstream.
  
So I would argue that this is the best solution. The current situation causes confusion, IMO.

**Comment by smarter** [comment]
Things get more complicated when you have some Java code that depends on some Scala code and some Scala code that depends on some Java code.

**Comment by jvican** [comment]
Things can get complicated, but I believe this solution sheds more light on the underlying problem. It's at least the only thing we can do in Zinc to clarify the situation no matter which Scalac version developers use.
  
I'm open to discuss better ways to solve this upstream. Do you have any concrete suggestion on how to approach this problem?

**Comment by smarter** [comment]
We'd need to define what "the problem" is concretely first. The issue only says:
> Scala's Java parser is not 100% compatible and some tools do not report Java parser errors coming from the Scala compiler (like Scala IDE)

So fix bugs in the scalac Java parser and fix tools that do not report some of the messages from scalac (that seems very weird to me). Once scalac compilation succeeds, javac is always be run anyway, so there is no chance of missing some javac-specific problem.

**Comment by smarter** [comment]
I really think this discussion needs some concrete examples of problematic code, otherwise we're just going to invent solutions to non-existent problems.

**Comment by jvican** [comment]
Check [this ScalaIDE bug report](https://app.assembla.com/spaces/scala-ide/tickets/1000361-false-error-compiling-java-non-static-inner-class/details).
  
I've experienced myself issues with the Java parser. An example of such an issue happened some days ago in this repository: we depended on Java 8 features and were using Scala 2.10.x, whose Java parser was not yet supporting JDK8 features. It's not about Java parser bugs, it's also about catching this kind of "compatibility issues".

**Comment by smarter** [comment]
OK, so as a workaround for a bug in the scalac Java parser, the Scala IDE stopped reporting all messages from that parser. And as a workaround for that, zinc is now going to run javac in more situations potentially reporting incorrect messages when your Scala code didn't compile? I fear the tower of workaround will never end this way.

>  we depended on Java 8 features and were using Scala 2.10.x, whose Java parser was not fixed to support them

So how do you fix that without updating scalac and without stopping using these features?

**Comment by jvican** [comment]
> So how do you fix that without updating scalac and without stopping using these features?
  
You fix it by running the Java compiler. The user will see that Javac has generated class files and scalac has failed. So scalac has failed. This is an improvement over the current situation: where you don't know if scalac is legitimately reporting an error. As I said before, this is Scalac version independent. 
  
Also, we must acknowledge that is more common that Scala sources depend on Java sources rather than the other way around, or the mixed mode. In this case, java sources will be successfully compiled always even if Scala Java's parser fails to run.
  
>  I fear the tower of workaround will never end this way.
  
I don't feel this is a workaround. It's really what Zinc should be doing.

**Comment by smarter** [comment]
> You fix it by running the Java compiler. The user will see that Javac has generated class files and scalac has failed. So scalac has failed. This is an improvement over the current situation: where you don't know if scalac is legitimately reporting an error. As I said before, this is Scalac version independent.

I don't think users usually look at generated classfiles this much. Furthermore, how do you know that the generated classfiles come from this round of compilation and are not a leftover from a previous compilation? It seems like a possible solution to the problem would be to clearly label in the reported messages which one come from scalac and which one come from javac.

> Also, we must acknowledge that is more common that Scala sources depend on Java sources rather than the other way around, or the mixed mode.

I don't know if that's actually true, but I do know that many big Scala projects have Java API wrappers that depend on the Scala API:
https://github.com/akka/akka/blob/master/akka-typed/src/main/scala/akka/typed/javadsl/Actor.scala
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/Configuration.java
https://github.com/lagom/lagom/blob/master/service/javadsl/integration-client/src/main/java/com/lightbend/lagom/javadsl/client/integration/LagomClientFactory.java
etc.

For all of these projects, trying to compile with javac when scalac failed can be misleading in multiple ways: you may get errors because the scalac classfile are not present, or even worse, because some scalac classfiles from a previous compilation run are present, this could be seriously confusing.

**Comment by fommil** [comment]
If the project isn't really mixed mode, then the user should set it as java first, then scala. If scala compilation fails in a mixed mode compile, I don't think anything can be reasonably said about the java compile.

FWIW, I have tended to work in projects where the java depended on the scala. e.g. a legacy SOAP app that was using scala to provide some endpoints. In my experience, the spread of mixed / java-first / scala-first is roughly equal.

**Comment by SethTisue** [comment]
I agree with @smarter.

**Comment by SethTisue** [comment]
And, I second the remarks about Java code depending on Scala code in mixed projects not being so rare. One of the main use cases for mixed compilation is legacy codebases where you don't want to worry about which parts of the code have been converted to Scala and which haven't yet.

(In greenfield code you may not need mixed-mode compilation at all; if you have e.g "Java API wrappers that depend on the Scala API", subprojects works fine for that... though you might go mixed-mode anyway, simply for convenience, if engineering your build to keep compilation separate is daunting or just a bother.)

**Comment by jvican** [comment]
I've read again this discussion and I've changed my mind. It looks like @smarter's proposal is the way to go. Scalac should report java parser errors with a special message that makes them obvious they come from Scalac and not Javac.
  
> It seems like a possible solution to the problem would be to clearly label in the reported messages which one come from scalac and which one come from javac.
