### ISSUE TITLE
CI build times have regressed because of bug in sbt 1.0

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#353]
CI build times have gone from 10 min to 23: https://platform-ci.scala-lang.org/sbt/zinc/98. :cry: 
  
This has to do with sbt 1.0.0-M6 not caching the update reports and executing them every time. This is a major bug that we should fix before RC, because it supposes a major regression in users' workflow and nobody will cross-compile to RC if this bug still persists.
  
To close this issue, we should update the sbt 1.0 version to one that solves this issue.

**Comment by dwijnand** [comment]
Tracked upstream as https://github.com/sbt/sbt/issues/3226.

**Comment by jvican** [comment]
Looking forward to updating to RC to fix this.
