### ISSUE TITLE
Use latest neo-sbt-scalafmt

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#372]
Use sbt 1.0.0-RC2.

Currently blocked by:
- https://github.com/thesamet/sbt-protoc/pull/30
- and ideally https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/34

**Comment by joeycozza** [comment]
@dwijnand we merged and cut a release for https://github.com/lucidsoftware/neo-sbt-scalafmt/pull/34
Test it out and let me know how it goes.  v1.9

**Comment by dwijnand** [comment]
Thank you, @joeycozza.
