### ISSUE TITLE
Don't publish the benchmark project

### ISSUE THREAD

**Issue by xuwei-k** [sbt/zinc#375]
http://repo1.maven.org/maven2/org/scala-sbt/benchmarks-of-zinc-and-the-compiler-bridge_2.12/

**Comment by jvican** [comment]
Mind sending a fix?

**Comment by jvican** [comment]
I'm surprised this is happening because `zincBenchmarks` already has:
```scala
    publish := {},
    publishLocal := {}
```
  
Anyway, I'm adding a fix to this on top of https://github.com/sbt/zinc/pull/377.
