### ISSUE TITLE
We should allow clients to overriding classpath hashing

### ISSUE THREAD

**Issue by romanowski** [sbt/zinc#400]
Zinc has a lot hooks to improve incremental compilation performance in case of really big projects. However when we hash classpath we just do tons of IO operations without  any way to e.g. reuse libs hashed before.

In case of 100+ projects with 100+ libs and on slower IO (e.g. windows) it takes a while **during each compilation (even no-op ones)**.

I haven't found a way to do it  without breaking binary compatibility but simple proposal how it can be done is here: https://github.com/romanowski/zinc/tree/hashing-classpath-proposal  

@stuhood I think pants may also benefit from caching classpath hashes.

**Comment by jvican** [comment]
Related to https://github.com/sbt/zinc/pull/371.
  
I agree this is a legit use case.
