### ISSUE TITLE
Provide a thread-safe version of `AnalysisCallback`

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#405]
`AnalysisCallback` is as of now not thread-safe. In @dragos's words:
>  Since we run several workers at the same time, and each worker has its own Global and analysis extraction logic, they perform updates concurrently. We used to override the compileIncrementalTask and fork some parts of Sbt to get to call our own implementation, but I think there should be a cleaner way, especially since xscbti.AnalysisCallback is an interface so it would be nice to be able to provide a different implementation.
  
This feature enables future parallel Scala compilers (like [Hydra](https://www.triplequote.com/hydra/)) to use the incremental compiler out of the box.
  
The place where the implementation should be provided is https://github.com/sbt/zinc/blob/1.x/internal/zinc-core/src/main/scala/sbt/internal/inc/Compile.scala, probably in an independent file.
  
The tests can be added in the `zincCore` project.

**Comment by dragos** [comment]
I didn't check yet, but I have the impression IntelliJ would need their own implementation of `AnalysisCallback` as well. Maybe a simple way to specify it from the outside would be enough, even if Zinc itself doesn't provide a thread-safe version.

**Comment by romanowski** [comment]
So far Intellij uses custom version of zinc based on 0.13.5 but AFAIK it will be migrated to zinc 1.0.
Intelliij.

Zinc is also used as scalac provider even if Intellij incremental compiler is used (and I think this was your case). [Here](https://github.com/JetBrains/intellij-scala/blob/idea172.x/jps-plugin/src/org/jetbrains/jps/incremental/scala/local/IdeaIncrementalCompiler.scala#L56-L66) you can find a piece of code that should be thread safe in current version and [here](https://github.com/JetBrains/intellij-scala/blame/idea173.x/jps-plugin/src/org/jetbrains/jps/incremental/scala/local/IdeaIncrementalCompiler.scala) code after migration to zinc 1.0.

cc @jastice
