### ISSUE TITLE
Javadoc returns a non-zero exit code but success is reported

### ISSUE THREAD

**Issue by raboof** [sbt/zinc#414]
In `sbt.inc.Doc`, the `javadoc` `JavaTool` is invoked.

When `javadoc` fails it produces a non-zero exit code, which leads to `run` returning `false`. In `Doc`, however, the return value is ignored.

**Comment by jvican** [comment]
Thanks for filing this bug @raboof. Please, next time you file a ticket, choose a meaningful title that explains clearly the issue, we try to keep the issue tracker clean and easy to read. 😄

**Comment by raboof** [comment]
What would be the proper way to report the error here? Is throwing acceptable or is there a better mechanism?

**Comment by jvican** [comment]
An exception would be the way to go. I encourage you to whip up a quick PR and we move forward from there. I guess that if Javadoc produces a non-zero exit code it also produces some kind of error messages. Is that displayed to the console as expected?

**Comment by raboof** [comment]
Will do!

The Javadoc error messages are indeed mostly-correctly printed to the console (but #415 ;) )

**Comment by raboof** [comment]
Fixed with #625 which should be released with sbt 1.3.0
