### ISSUE TITLE
Javadoc may not log all errors

### ISSUE THREAD

**Issue by raboof** [sbt/zinc#415]
When debugging an instance where javadoc produced the error "javadoc: error - invalid flag: -target", this error was not printed on `javacLogger.flush(exitCode)`.

It was correctly added to `JavacLogger.msgs` with level `error`, so I'd expect `parseAndDumpSemanticErrors` to fail to parse it and log it instead, not sure why that doesn't appear to be happening.

**Comment by jvican** [comment]
@raboof Any ideas how we can reproduce/test this?

**Comment by raboof** [comment]
Like https://github.com/raboof/zinc/commit/6253ceec9246d73b66bfdf7354275484dd194d8f ?

**Comment by jvican** [comment]
That looks good. Hopefully we fix this soon. Thanks @raboof! :smile:

**Comment by jvican** [comment]
Closing in favor of https://github.com/sbt/zinc/issues/520 which is richer in details. We'll add the provided reproduced case in this ticket to our test suite, thank you @raboof
