### ISSUE TITLE
Investigate trait-private-object, trait-private-var, and trait-super

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#420]
189a2a52042535dcb830cece29f26ad2a99df759 reverted 7956aba and also marked three scripted tests as pending. In other words, those tests are currently failing, likely causing under compilation.

Ref https://github.com/sbt/sbt/pull/2160

**Comment by jvican** [comment]
I'm taking this one, it was in my TODO list for a long time.

**Comment by jvican** [comment]
Fixed in https://github.com/sbt/zinc/pull/542
