### ISSUE TITLE
Remove heuristic to recompile all when 50% of sources have changed in tests

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#430]
https://github.com/sbt/zinc/pull/424/files has detected that `patMat-scope` is invalidating all sources when it works locally. As a safety measure, we should remove the heuristic to recompile all when 50% of sources have changed for scripted tests so that we're not bitten by this again. Who knows if we're not falling prey of this now and we don't know it.

**Comment by Friendseeker** [comment]
Fixed in https://github.com/sbt/zinc/pull/533
