### ISSUE TITLE
Update to Scala 2.12.4

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#437]
I will create a PR to update the project to Scala 2.12.4 and make the changes to handle constants: https://github.com/sbt/zinc/issues/227.

**Comment by mkurz** [comment]
Scala 2.12.4 is out

**Comment by dwijnand** [comment]
Done in #458. I've added #227 to milestone "1.something" (https://github.com/sbt/zinc/milestone/10) to try and remember to do it now that we're using Scala 2.12.4.
