### ISSUE TITLE
Add yourkit to the README to get free licenses

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#447]
Yourkit asks open-source projects to add their logo in the README of their projects in exchange for licenses. I've already asked them, so all is missing is a PR adding that. I've asked for a license to every Zinc developer.
  
 This issue is to keep track of any discussion concerning this and of the future PR I'll do when I find some time. @eed3si9n Im assigning you to the ticket as well so that you voice the opinion of the sbt team on this move before it happens.

**Comment by eed3si9n** [comment]
+1 from me.

**Comment by fommil** [comment]
Gratis, not free.

**Comment by Friendseeker** [comment]
May I also get a license?

I was looking into analyzing Zinc performance and this would potentially be really helpful.

**Comment by eed3si9n** [comment]
There's been a bunch of free (if not free-of-charge) profiling tools that I haven't really used YourKit lately. https://github.com/sbt/sbt/blob/1.10.x/PROFILING.md lists some of them. Having said that, we can contact YourKit team and get the licenses again for the current batch of Zinc team.

**Comment by Friendseeker** [comment]
> There's been a bunch of free (if not free-of-charge) profiling tools that I haven't really used YourKit lately. https://github.com/sbt/sbt/blob/1.10.x/PROFILING.md lists some of them. Having said that, we can contact YourKit team and get the licenses again for the current batch of Zinc team.

Thanks! Glad to see that free alternatives exist and are well-documented!

I will try the free alternatives first then.

**Comment by eed3si9n** [comment]
So apparently there is an active license with available seats. @jvican Do you have info on this? I don't remember who applied for it last.
