### ISSUE TITLE
zinc 1.0.0 - 1.0.3 published using JDK8

### ISSUE THREAD

**Issue by stuhood** [sbt/zinc#451]
It looks like recent versions of zinc were published using JDK8, with source/target set to 8. When Java code is built (as in the case of all of the `xsbti` classes), the result is classfile version `52.0`, which is not usable on older JVMs:
```
javap -classpath .pants.d/ivy/jars/org.scala-sbt/zinc-compile-core_2.11/jars/zinc-compile-core_2.11-1.0.3.jar  -verbose xsbti/ReporterUtil | grep "major"
  major version: 52
```

There is likely a simple tweak to the build to set the source/target versions to 7, but I don't know enough about sbt builds to know what it would be.

**Comment by dwijnand** [comment]
I've no (real) experience playing with source/target, but I'm not sure we can target anything less than Java 8 given we depend on JDK 8 classes like java.util.Optional: https://github.com/sbt/zinc/pull/304/commits/686b6bb174fe76390646a7e7770914906fefc2f1

**Comment by stuhood** [comment]
Aha. Yep, had totally forgotten about that. Whelp... not much to do then. Closing!
