### ISSUE TITLE
How to use zinc with play - scala -maven plugin?

### ISSUE THREAD

**Issue by tenstriker** [sbt/zinc#483]
Can someone write some document or point to existing one on how to use Zinc in general when not using SBT. We have a scala - maven project with scala-maven plugin by davidB and play-maven plugin. We run and test our application from Scala IDE. It'd be nice if we can find a working Incremental compilation with this setup . Seems like it can be possible by using zinc but not sure how. It

**Comment by eed3si9n** [comment]
Zinc is an incremental compiler library, so you'd need to have your Maven plugin author adopt it.
Recently there was a new Maven plugin came out that uses Zinc, so you could try it out - https://github.com/random-maven/scalor-maven-plugin
