### ISSUE TITLE
tests fail in dbuild context (sbt.internal.inc.InvalidComponent)

### ISSUE THREAD

**Issue by SethTisue** [sbt/zinc#485]
I get a bunch of messages like "sbt.internal.inc.InvalidComponent: The compiler bridge sources org.scala-sbt:compiler-bridge_2.12:1.1.0-dbuildxbf579d40cbffdff1fd1e72ea5565b14e328a9c02\
:compile could not be retrieved"

looks like some version number logic is confused by dbuild's mangled version numbers

I will work around it for now by disabling the zincIvyIntegration tests in the community build

full log at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2548/consoleFull

**Comment by SethTisue** [comment]
in the `zinc` project I also get:

```
[zinc] [error] Failed tests:
[zinc] [error] 	sbt.inc.MultiProjectIncrementalSpec
[zinc] [error] 	sbt.inc.NameHashingCompilerSpec
[zinc] [error] 	sbt.inc.cached.CachedHashingSpec
[zinc] [error] 	sbt.inc.ClasspathHashingHookSpec
[zinc] [error] 	sbt.inc.IncrementalCompilerSpec
[zinc] [error] 	sbt.inc.NestedJavaClassSpec
[zinc] [error] Error during tests:
[zinc] [error] 	sbt.inc.cached.ProjectRebaseCacheSpec
[zinc] [error] 	sbt.inc.cached.ExportedCacheSpec
```

with a bunch of messages that say:

```
sbt.internal.inc.InvalidComponent: The Scala compiler and library could not be retrieved.
```

full log at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2549/consoleFull

**Comment by jvican** [comment]
I have trouble seeing where the issue is. Can you elaborate a little bit @SethTisue ? Is this something we must fix in our build, is this a bug caused by sbt or is this caused by the `scalaHome` and other specific changes that you do in dbuild?

**Comment by SethTisue** [comment]
I really don't know, couldn't even begin to guess.

**Comment by jvican** [comment]
Oh, I get what's happening now. Yeah, it looks like this is a problem in our build, and dbuild's version is causing the build not to publish the bridges to the correct place (because our build has a specific location for them that is not the ivy cache IIRC).

**Comment by jvican** [comment]
This has change with the new refactoring in the build, so it shouldn't be an issue. If it is, please reopen.

**Comment by SethTisue** [comment]
@jvican same errors

**Comment by jvican** [comment]
Where can I modify the code use for zinc? The build should run `publishBridges` before running tests

**Comment by SethTisue** [comment]
trying that out over at https://github.com/scala/community-builds/pull/778

**Comment by SethTisue** [comment]
Unlikely to ever progress. If full testing of Zinc against Scala nightlies (all of them, or just the release candidates) is desired, I'd suggest doing that in Zinc's own CI.

The most recent effort in this area was https://github.com/scala/community-build/pull/1280, but it stalled.
