### ISSUE TITLE
Drone CI is stuck

### ISSUE THREAD

**Issue by dwijnand** [sbt/zinc#504]
looks like https://platform-ci.scala-lang.org/sbt/zinc is stuck, blocking all PRs

possibly related to disk space problems as reported in https://github.com/sbt/zinc/pull/498#issuecomment-367580544?

here's a screen shot the current state:

![image](https://user-images.githubusercontent.com/344610/36832420-540f8f88-1d23-11e8-9cef-d62673efcd98.png)

@jvican please can you take care of this?

**Comment by jvican** [comment]
Everything is back to normality, docker got crazy and a restart made everything work again. Thanks for the ticket @dwijnand.

**Comment by dwijnand** [comment]
thank you Jorge
