### ISSUE TITLE
Dependency#DependencyTraverser#traverse does not take `classOf` expressions into account

### ISSUE THREAD

**Issue by natansil** [sbt/zinc#508]
I've found a case where the dependency expression is missed by the [tree traversal pattern matching](https://github.com/sbt/zinc/blob/1.x/internal/compiler-bridge/src/main/scala/xsbt/Dependency.scala#L332).

the expression is of kind: `classOf[some-class]`. e.g.: 
`classOf[org.apache.commons.lang3.ArrayUtils]`
None of the current cases (`Import`, `Select`, `TypeTree`, etc.) matches.

A possible fix can be to add the following `case` in the pattern matching clause:
 `case Literal(value) if value.tag == ClazzTag => addTypeDependencies(value.typeValue)`

**Comment by natansil** [comment]
CC: @gkk-stripe

**Comment by jvican** [comment]
Great find! Mind sending a PR?

**Comment by dwijnand** [comment]
fixed in #510. due in zinc (and sbt) 1.2.0.
