### ISSUE TITLE
v 1.1.3 missing from maven-central

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [sbt/zinc#515]
https://github.com/sbt/zinc/releases/tag/v1.1.3

https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/

**Comment by eed3si9n** [comment]
Duplicate of https://issues.sonatype.org/browse/MVNCENTRAL-3257

**Comment by Andrei-Pozolotin** [comment]
perhaps should post warning on https://github.com/sbt/zinc/releases/tag/v1.1.3

**Comment by dwijnand** [comment]
@eed3si9n let us know if there's any news on that issue because it's not publicly visible:

![image](https://user-images.githubusercontent.com/344610/37898772-9d12d11e-30e1-11e8-9285-5d109ac395b9.png)

**Comment by Andrei-Pozolotin** [comment]
@eed3si9n can we trust this? :-)
https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.1.3/

**Comment by eed3si9n** [comment]
@dwijnand No update on the issue.

@Andrei-Pozolotin Yes! Thanks

**Comment by Andrei-Pozolotin** [comment]
@eed3si9n  please remove
https://github.com/sbt/zinc/releases/tag/v1.1.3
```
Note: 1.1.3 hasn't synced to Maven Central yet.
```

**Comment by dwijnand** [comment]
@Andrei-Pozolotin done
