### ISSUE TITLE
Add JDK 11 testing

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#540]
https://github.com/sbt/zinc/issues/538 is an example where things works on JDK 8, but failed on JDK 9. We should add testing for JDK 10 and 11-ea.

- [x] DocSpec "Doc.cachedJavadoc should throw when generating javadoc fails" (failing due to Scala 2.10)
- [x] MultiProjectIncrementalSpec "incremental compiler should detect shadowing" (failing due to Scala 2.11)
- [x] JavaCompilerSpec "Compiling a java file with local javac should compile a java file"
- [x] JavaCompilerSpec "Compiling a java file with local javac should issue errors and warnings"
- [x] JavaCompilerSpec "Documenting a file with forked javadoc should find errors in a java file"
- [x] ZincBenchmarkSpec NPE
- [x] ZincComponentCompilerSpec "should compile the bridge for Scala 2.10.5 and 2.10.6" (failing due to Scala 2.10) 
- [x] ZincComponentCompilerSpec  "should compile the bridge for Scala 2.11.8 and 2.11.11"
- [x] scripted source-dependencies / ext

**Comment by Andrei-Pozolotin** [comment]
java-10 on travis: https://github.com/travis-ci/travis-ci/issues/9368

java-10 on appveyor: https://github.com/appveyor/ci/issues/2195

**Comment by eed3si9n** [comment]
Thanks. We currently use Drone for Zinc's CI.

**Comment by jvican** [comment]
@eed3si9n @Andrei-Pozolotin do you feel like adding support for this now that sbt 1.2.1 supports it?

**Comment by eed3si9n** [comment]
I think we definitely should try adding JDK 11-ea testing.
What do we need to do to spawn more drone jobs?

**Comment by adriaanm** [comment]
+1 on testing on Java 11. I'm using it myself now to have some skin in that game, and it looks like zinc is recompiling more files than usual. Haven't investigated though.

**Comment by SethTisue** [comment]
fwiw, Jorge and I have been working (slowly, as a back burner task) on getting zinc's tests running in the Scala 2.12/JDK9 and JDK10 community builds over at https://github.com/scala/community-builds/pull/778 (and I'll be replacing the 9 and 10 builds with an 11 build before too much longer)

**Comment by xuwei-k** [comment]
https://github.com/sbt/zinc/pull/602

**Comment by eed3si9n** [comment]
@jvican #640 passes the tests locally, but on Drone it's currently erroring with

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f00f1f23351, pid=107, tid=926
#
# JRE version: Java(TM) SE Runtime Environment (11.0+28) (build 11+28)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (11+28, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xc03351]  Node::add_req(Node*)+0xc1
#
# Core dump will be written. Default location: /drone/src/github.com/sbt/zinc/core
#
# An error report file with more information is saved as:
# /drone/src/github.com/sbt/zinc/hs_err_pid107.log
#
# Compiler replay data is saved as:
# /drone/src/github.com/sbt/zinc/replay_pid107.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
/usr/lib/bin/sbt: line 217:   107 Aborted                 (core dumped) "$@"
```

**Comment by eed3si9n** [comment]
Here's a PR to change the Docker image - https://github.com/scalacenter/docker-scala/pull/4
