### ISSUE TITLE
intermittent failure in BinaryAnalysisFormatSpecification

### ISSUE THREAD

**Issue by SethTisue** [sbt/zinc#564]
seen at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3238/consoleFull

```
[zinc] [info] + TextAnalysisFormat.Write and read empty Analysis: OK, proved property.
[zinc] [info] ! BinaryAnalysisFormat.Write and read complex Analysis: Exception raised on property evaluation.
[zinc] [info] > ARG_0: Analysis: 5 Scala sources, 30 classes, 5 external source dependencies
[zinc] [info] > Exception: java.lang.NullPointerException: null
```

**Comment by jvican** [comment]
We cannot act on this, and the tests are passing in our CI, so I'm closing. We can reopen if we find a way to reproduce the error.

**Comment by SethTisue** [comment]
okay. I can exclude the test from the community build if the failure keeps cropping up.

**Comment by jvican** [comment]
If it happens again, let me know and I’ll try to find a way to reproduce it
