### ISSUE TITLE
ClassCanonicalNameSpec fails on JDK 9

### ISSUE THREAD

**Issue by SethTisue** [sbt/zinc#567]
```
[zinc] [info] - should for O-O-O (tag) return x.y$$z$ *** FAILED ***
[zinc] [info]   "x.y$[.]z$" did not equal "x.y$[$]z$" (ClassCanonicalNameSpec.scala:27)
```

and a bunch of other such failures turned up in the Scala community build at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-jdk9-integrate-community-build/353/consoleFull

**Comment by eed3si9n** [comment]
I have a PR for this https://github.com/sbt/zinc/pull/639
