### ISSUE TITLE
Add an AuxiliaryClassFileManager to Zinc public API

### ISSUE THREAD

**Issue by allanrenucci** [sbt/zinc#579]
From scala-js/scala-js#3419:

> Can we upstream a more generic version of https://github.com/lampepfl/dotty/blob/master/sbt-dotty/src/dotty/tools/sbtplugin/TastyFileManager.scala to Zinc so that scala-js and others can reuse it instead of reimplementing it?

I think we need something like:
```scala
abstract class AuxiliaryClassFileManager extends ClassFileManager {

  /** Given a list of class files, return the list of associated files
   *
   *  Associated files share the same life cycle as their class file.
   *  E.g. if a class file is deleted or restored, its associated files will
   *  be deleted or restored as well.
   */
  protected def associatedFiles(classes: Array[File]): Array[File]
}
```

**Comment by sjrd** [comment]
Yes, that would be an ideal API for us in Scala.js.

(I think you can make `associatedFiles` protected rather than public)

**Comment by sjrd** [comment]
Or perhaps even better: just give me one `.class` file at a time:
```scala
protected def associatedFiles(classFile: File): Array[File]
```

**Comment by smarter** [comment]
@eed3si9n @dwijnand I'd like to bring attention to this issue again: ClassFileManager in 1.4 now uses VirtualFile and it's not clear to me if that still allows the sbt-dotty and sbt-scalajs plugin to correctly implement a custom ClassFileManager. https://github.com/sbt/zinc/pull/902 restores the old API as deprecated which should at least help with migration but doesn't seem like it's a good way forward.
