### ISSUE TITLE
Removing default value of case class constructor doesn't invalidate usages

### ISSUE THREAD

**Issue by jrudolph** [sbt/zinc#594]
I'm seeing an issue when removing a default value for a top-level case class field. This doesn't invalidate and rebuild any files (in the same project) that depended on the default value being present.

The project uses sbt 1.2.1 / scala 2.12.6.

It can be reproduced by compiling akka-http at https://github.com/akka/akka-http/pull/2185/commits/ce622a16a8fa22a72dfc4121695805ae9a7436f7 and then removing the default parameter value from `EntityStreamSizeException.actualSize` which doesn't trigger any downstream recompilations at the usage sites.

When `akka-http-tests/testOnly akka.http.scaladsl.server.SizeLimitSpec` is run `java.lang.NoSuchMethodError: akka.http.scaladsl.model.EntityStreamSizeException$.apply$default$2()Lscala/Option;
` is thrown.

I'll try to come up with a reproducer.

(I first thought it might be related to #559 but from @jvican's analysis so far, this one seems to be a broader issue.)

**Comment by jvican** [comment]
Thanks @jrudolph I’ll have a look at this on Thursday.

**Comment by jrudolph** [comment]
Thanks, @jvican, I'll try to minify until then.

**Comment by jrudolph** [comment]
It's as simple as that:

Main.scala:

```scala
object Main extends App {
  println(A())
}
```

A.scala:

```scala
case class A(value: Int = 0)
```

Compile first with the default parameter. Then remove it and only A.scala will be recompiled.

**Comment by jrudolph** [comment]
It's interesting that the api diff doesn't even seem to know about the case class apply methods:

```
[debug] [diff] object A extends  {
[debug] [diff] 
[debug] [diff] 
[debug] [diff] 
[debug] [diff] }
```

**Comment by jvican** [comment]
At first sight it looks quite familiar to the bug I fixed one week ago, but in that one the api change in the synthetic default methods was correctly reported by zinc.
