### ISSUE TITLE
Replace dependency on sbt/lm with Coursier

### ISSUE THREAD

**Issue by dwijnand** [sbt/zinc#614]
There's a small amount of Zinc that requires on being able to fetch dependencies.  To satisfy that requirement Zinc depends on sbt's internal "library management" (LM) module https://github.com/sbt/librarymanagement, which in turn depends on sbt's internal "util" module https://github.com/sbt/util and finally sbt's internal io module https://github.com/sbt/io.  LM also depends on Ivy, and there's an ongoing effort to provide an alternative backing implementation based on Courser.

I think it would be mututally benefitial to sbt and zinc if the dependency between zinc and sbt's internal modules were cut, by replacing LM with Coursier, and other (historical or accidental) usages of sbt internals with alternatives (NIO.2, etc).

For Zinc it would probably mean better perfomance, easier to request and obtain any feature requests or enhancements from Coursier.

For sbt it would mean being able to re-integrate those internal modules back into the sbt/sbt repo, which would greatly improve sbt's development.

**Comment by dwijnand** [comment]
(Wasn't sure about the meaning of some of the labels, so I opted-in, so they can be dropped if not appropriate.  Particularly "build", "infrastructure", "upkeep", and "performance", not documented in https://github.com/sbt/zinc/wiki/Use-of-labels. Also "feature"? 🤷‍♂️).

**Comment by eed3si9n** [comment]
It would be good to list out Zinc's use of any transitive usage of sbt modules apart from lm.

**Comment by dwijnand** [comment]
Well most probably the io module and util-logging.  But does it depend on AttributeKey, for instance or can that go back into sbt?
