### ISSUE TITLE
NullPointerException on sbt.internal.inc.binary.BinaryAnalysisFormat.writeAPIs

### ISSUE THREAD

**Issue by tanin47** [sbt/zinc#615]
- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

## steps

Use a git dependency in `project/plugins.sbt` as shown below: 

```
lazy val root = Project("plugins", file(".")).aggregate(sbtVueI18n).dependsOn(sbtVueI18n)

lazy val sbtVueI18n = RootProject(uri("git://github.com/GIVESocialMovement/sbt-i18n.git#f033c964a0b53d1b1aa10dc97328a612dc7d5425"))
```

## problem

```
[error] java.lang.NullPointerException
[error] 	at xsbti.api.SafeLazy$Impl.get(SafeLazy.java:58)
[error] 	at xsbti.api.Structure.inherited(Structure.java:32)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.toStructure(ProtobufWriters.scala:277)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.toClassLike(ProtobufWriters.scala:528)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.toCompanions$1(ProtobufWriters.scala:558)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.toAnalyzedClass(ProtobufWriters.scala:570)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.$anonfun$toApis$1(ProtobufWriters.scala:659)
[error] 	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error] 	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253)
[error] 	at sbt.internal.inc.schema.APIs.__computeSerializedValue(APIs.scala:19)
[error] 	at sbt.internal.inc.schema.APIs.serializedSize(APIs.scala:26)
[error] 	at sbt.internal.inc.schema.APIsFile.$anonfun$writeTo$1(APIsFile.scala:40)
[error] 	at sbt.internal.inc.schema.APIsFile.$anonfun$writeTo$1$adapted(APIsFile.scala:38)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at sbt.internal.inc.schema.APIsFile.writeTo(APIsFile.scala:38)
[error] 	at sbt.internal.inc.binary.BinaryAnalysisFormat.writeAPIs(BinaryAnalysisFormat.scala:31)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1(FileAnalysisStore.scala:91)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1$adapted(FileAnalysisStore.scala:83)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.internal.inc.FileAnalysisStore$BinaryFileStore.set(FileAnalysisStore.scala:83)
[error] 	at sbt.internal.inc.AnalysisStore$CachedAnalysisStore.set(AnalysisStore.scala:27)
[error] 	at sbt.internal.inc.AnalysisStore$SyncedAnalysisStore.set(AnalysisStore.scala:39)
[error] 	at sbt.Defaults$.$anonfun$compileTask$1(Defaults.scala:1400)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:272)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (ProjectRef(uri("git://github.com/GIVESocialMovement/sbt-i18n.git#f033c964a0b53d1b1aa10dc97328a612dc7d5425"), "sbt-i18n") / Compile / compile) java.lang.NullPointerException
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? Exited with code 1
```

This error occurs on our CI around 1 in 10 times.

## expectation

I'd expect it not to have an error.

## notes

sbt version: 1.1.5

**Comment by tuures** [comment]
This is happening on our CI roughly once every 10-20 builds. 
SBT 1.2.8

**Comment by hvesalai** [comment]
Our stacktrace is a bit different:

```
[error] java.lang.NullPointerException
[error] 	at xsbti.api.SafeLazy$Impl.get(SafeLazy.java:62)
[error] 	at xsbti.api.Structure.declared(Structure.java:29)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.toStructure(ProtobufWriters.scala:287)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.toClassLike(ProtobufWriters.scala:539)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.toCompanions$1(ProtobufWriters.scala:571)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.toAnalyzedClass(ProtobufWriters.scala:583)
[error] 	at sbt.internal.inc.binary.converters.ProtobufWriters.$anonfun$toApis$1(ProtobufWriters.scala:677)
```

**Comment by hvesalai** [comment]
I guess this is a traditional race. SafeLazy is not thread safe.

https://github.com/sbt/zinc/blob/develop/internal/compiler-interface/src/main/java/xsbti/api/SafeLazy.java#L51

Here the constructor sets the thunk and then here the nupo is thrown:

https://github.com/sbt/zinc/blob/develop/internal/compiler-interface/src/main/java/xsbti/api/SafeLazy.java#L62

If the `get` is called on an `SafeLazy.Impl` before the constructor has been fully run (which is allowed by JVM), then you would get this exception.

The other possibilities are that somebody has constructed a `SafeLazy.Impl` with `null` `thunk`, or that somebody is calling a `SafeLazy.Impl` twise (since the first call will set the `thunk` to `null`) again in a thread-unsafe way (since `SafeLazy.Impl.get` will try to set the flag to signal that the `result` is there).

As a side note: the `SafeLazy.Impl` could be made simpler by removing the `flag` and merely checking if `thunk` is null or not (if null, result has been set). Also an assert to check that the `thunk` supplied to the constructor is not null would be good.

**Comment by hvesalai** [comment]
@eed3si9n you know how this should work. Is the problem that single threaded code is being run by two threads (so we should somehow restrict the level of concurrency in sbt), or is the problem that the zinc code should be, but is not, thread safe?

I can easily make a PR to make the SafeLazy thread safe if that is intentional.

**Comment by cspeckmim** [comment]
I just came across this same issue with sbt 1.2.8. Workaround is to re-run the sbt task.
[exception.txt](https://github.com/sbt/zinc/files/4077814/exception.txt)

**Comment by eatkins** [comment]
@hvesalai it is not at all clear to me why `SafeLazy` is not thread safe. The original version of that class was implemented in scala and was thread safe. Making it thread safe with double checked locking seems straightforward. Perhaps @jvican can chime in on why the `SafeLazy` implementation in java is deliberately not thread safe?

**Comment by hvesalai** [comment]
@eed3si9n @jvican can you please say something here. This bug is causing our multi-project build to fail daily on Jenkins (since it does always clean builds, which causes lot of parallelism, unlike normal builds).

**Comment by eed3si9n** [comment]
So as Ethan has noted SafeLazy became not thread safe in https://github.com/sbt/zinc/pull/221 deliberately:

> This implementation of lazy val assumes that `SafeLazy` will never be
called asynchronously. If this is the case, it's up to the Zinc
maintainer to make sure that safe publishing is implemented at the
call-site or to change the implementation to avoid races and
uninitialized fields.

It seems apparent from this bug that we haven't taken the latter steps to make sure the SafeLazy is never called concurrently. I think putting synchronization back sounds like a conservative fix.

**Comment by hvesalai** [comment]
Happy to report the fix has worked and we have no Nupos any more.
