### ISSUE TITLE
Add support for pipelining

### ISSUE THREAD

**Issue by jvican** [sbt/zinc#650]
This week I'll be adding support for pipelining in sbt/zinc based on all the work that I've done in bloop and several months of experimentation.
  
Pipelining support is not a big deal and will be only a few hundred lines of code. The most challenging aspect of pipelining is done by the build tool who drives it.

**Comment by julienrf** [comment]
Any update on this? There have been a couple of weeks without news.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/zinc/pull/744 and other PRs.
