### ISSUE TITLE
Maven pom contains duplicate repositories

### ISSUE THREAD

**Issue by brewerja** [sbt/zinc#666]
Gradle doesn't handle including zinc because it complains that the pom.xml has duplicate repositories. The id `bintraysbtmavenreleases` is included twice.

Example: http://central.maven.org/maven2/org/scala-sbt/zinc_2.12/1.2.5/zinc_2.12-1.2.5.pom

```xml
<repositories>
    <repository>
        <id>bintraysbtmavenreleases</id>
        <name>bintray-sbt-maven-releases</name>
        <url>https://dl.bintray.com/sbt/maven-releases/</url>
        <layout>default</layout>
    </repository>
    <repository>
        <id>sonatypesnapshots</id>
        <name>sonatype-snapshots</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    <layout>default</layout>
    </repository>
    <repository>
        <id>bintraysbtmavenreleases</id>
        <name>bintray-sbt-maven-releases</name>
        <url>https://dl.bintray.com/sbt/maven-releases/</url>
        <layout>default</layout>
    </repository>
</repositories>
```

Gives the following error when building:
```
Errors occurred while build effective model from <GRADLE_HOME>/caches/modules-2/files-2.1/org.scala-sbt/zinc-core_2.12/1.2.5/dc217a9901557e3d01d95ebef629ad85c7a68269/zinc-core_2.12-1.2.5.pom:
    'repositories.repository.id' must be unique: bintraysbtmavenreleases -> https://dl.bintray.com/sbt/maven-releases/ vs https://dl.bintray.com/sbt/maven-releases/ in org.scala-sbt:zinc-core_2.12:1.2.5
```

**Comment by eed3si9n** [comment]
@brewerja Thanks for the report. We'll remove those.

**Comment by eed3si9n** [comment]
https://github.com/sbt/zinc/pull/667

**Comment by eed3si9n** [comment]
I realized I'd have to do the same for other submodules.

**Comment by Friendseeker** [comment]
c.c.

https://repo1.maven.org/maven2/org/scala-sbt/zinc_2.12/1.10.2/zinc_2.12-1.10.2.pom
https://repo1.maven.org/maven2/org/scala-sbt/zinc-core_2.12/1.10.2/zinc-core_2.12-1.10.2.pom
https://repo1.maven.org/maven2/org/scala-sbt/zinc-compile-core_2.12/1.10.2/zinc-compile-core_2.12-1.10.2.pom
https://repo1.maven.org/maven2/org/scala-sbt/zinc-classfile_2.12/1.10.2/zinc-classfile_2.12-1.10.2.pom

Not sure what Eugene's comment from 5 years ago meant but for now all submodules does not have `bintraysbtmavenreleases` in their `pom.xml` files
