### ISSUE TITLE
WriteReportingFileManager fails with  java.lang.IllegalArgumentException: Not supported: sbt.internal.inc.javac.WriteReportingJavaFileObject@3e42b4ef

### ISSUE THREAD

**Issue by pkolaczk** [sbt/zinc#684]
This issue has been already hit once: sbt/zinc#185, however I argue this hasn't been fixed properly, but only workaround by disabling `WriteReportingFileManager` by default.

Now I've hit the same problem with bloop's custom `JavaFileManager`:
https://github.com/scalacenter/bloop/issues/956

Because the custom `JavaFileManager` produces wrapped`FileObjects`, its `isSameFile` should unwrap the original `FileObject`s from `WriteReportingFileObjects` before passing them to the underlying file manager. 

I'll create a PR soon.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/zinc/pull/687
