### ISSUE TITLE
sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType

### ISSUE THREAD

**Issue by japgolly** [sbt/zinc#688]
## steps
Compile this:
```scala
object X {
  final case class Y(private[X] val i: Int) extends AnyVal
}
```

## problem
SBT emits warning:
```
[warn] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: blah.X.Y)Int
```

## expectation
No warning.

## notes
Using SBT 0.13.15 & Scala 2.12.2.

**Comment by eed3si9n** [comment]
Here's my PR - https://github.com/sbt/zinc/pull/689

**Comment by torkelrogstad** [comment]
Thank you!

**Comment by xuwei-k** [comment]
same error in Monocle with sbt 1.3.0

- https://github.com/julien-truffaut/Monocle/pull/698
- https://travis-ci.org/julien-truffaut/Monocle/jobs/580824040

```
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.PrismSyntax[S,A])monocle.Prism[S,A]
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.syntax.ApplyTraversalOps[S])S
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.syntax.ApplyIsoOps[S])S
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.syntax.ApplyGetterOps[S])S
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.syntax.ApplyOptionalOps[S])S
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.syntax.ApplyLensOps[S])S
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.syntax.ApplyFoldOps[S])S
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.syntax.ApplySetterOps[S])S
[error] sbt-api: Unhandled type class scala.reflect.internal.Types$MethodType : ($this: monocle.syntax.ApplyPrismOps[S])S
```

**Comment by dwijnand** [comment]
Maybe the message should be behind a flag, similar to scalac's `-Xdev`, for Zinc devs.

**Comment by nafg** [comment]
Hmm, for OP it was a warning but @xuwei-k reports it as an error

**Comment by eed3si9n** [comment]
Also it looks like sbt 1.3.0 bump has triggered this?

**Comment by xuwei-k** [comment]
> Hmm, for OP it was a warning but @xuwei-k reports it as an error

Monocle set `-Xfatal-warnings`

- https://github.com/xuwei-k/Monocle/commit/e7c5c80974fe5bda8e2d26cf61c307d8f85d2885
- https://travis-ci.org/xuwei-k/Monocle/builds/583457370

> Also it looks like sbt 1.3.0 bump has triggered this?

Yes 😭

**Comment by cquiroz** [comment]
Any chance the fix at https://github.com/sbt/zinc/pull/689 will be included?

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/zinc/pull/874/commits/105fcaa5c54c59bd6be819672f7e6b34e71bc852
