### ISSUE TITLE
failure to recognize dotty instance

### ISSUE THREAD

**Issue by martijnhoekstra** [sbt/zinc#695]
Dotty on windows cmd runs fine the first time, but when I change something and try to incrementally compile, it looks like zinc fails here: https://github.com/sbt/zinc/blob/f3825fb66ca72eebbbc7ee9a4f96fa919ff522b0/internal/zinc-classpath/src/main/scala/sbt/internal/inc/ScalaInstance.scala#L256

at least, it fails with that message.

in mingw so far so good.

**Comment by eed3si9n** [comment]
Dotty support is implemented by https://github.com/lampepfl/dotty's sbt plugin and the compiler bridge, so it might be better to report this there?

**Comment by martijnhoekstra** [comment]
I don't know exactly, I just reported where I traced the error to.

Do you mean I should support there? Or what are you asking me exactly?

**Comment by eed3si9n** [comment]
Yes. Please report this error to Dotty repo instead including the full stacktrace of the error.
