### ISSUE TITLE
Cross compile against Scala 2.13

### ISSUE THREAD

**Issue by slandelle** [sbt/zinc#697]
Hello,

Do you have any plans regarding cross compiling zinc for Scala 2.13 (just like up to 1.2.1 zinc was cross compiled for 2.11 and 2.12)?

Best regards

**Comment by eed3si9n** [comment]
I think we should be pretty close since there's sjson-new for Scala 2.13.
I'm guessing it's a matter of setting up the build with right dependencies?

**Comment by almothafar** [comment]
Any news for this release? https://github.com/sbt/zinc/issues/697 waiting for this, and https://github.com/gatling/gatling/issues/3566 waiting for that, nice chain :)

**Comment by almothafar** [comment]
Any news for this release? gatling/gatling#3566 waiting for this, and any project using gatling waiting for that, nice chain :)

**Comment by eed3si9n** [comment]
I actually tried a few days ago. I think what was missing was protobuf-related thing for the current version of ScalaPB that's being used. We could bump the version to the one that has 2.13 artifact, but it would likely require some changes.

**Comment by henricook** [comment]
I think this is blocking our project's adoption of Scala 2.13 - because we rely on Gatling and Gatling relies on this. Is there anything I can do to help?

If anyone knows how Gatling uses zinc / why it relies on zinc that'd be very illuminating for me as well

**Comment by slandelle** [comment]
> I think this is blocking our project's adoption of Scala 2.13 - because we rely on Gatling and Gatling relies on this.

Situation is a bit complex on our side. I've explained our situation [here](https://github.com/gatling/gatling/issues/3566#issuecomment-531018649).

> Is there anything I can do to help?

@eed3si9n, please correct me if I'm wrong, but this ticket is mostly upgrading from old [scalapb](https://github.com/sbt/zinc/blob/7b60eae85bcdd748aa9d84039e5c07cf1bf6cbc9/project/plugins.sbt#L9) to the [new one](https://scalapb.github.io/).

> If anyone knows how Gatling uses zinc / why it relies on zinc that'd be very illuminating for me as well

I've explained in the Gatling ticket (let's not pollute this ticket with purely Gatling related discussions).

**Comment by eed3si9n** [comment]
@slandelle Yea. Upgrading to new ScalaPB should unblock us to move forward.

**Comment by slandelle** [comment]
Hi there,
Now that ScalaPB has been upgraded, is there anything we can do to help moving this forward?

**Comment by eed3si9n** [comment]
I guess we can publish a milestone from the develop branch.

**Comment by slandelle** [comment]
Hi @eed3si9n Is having zinc cross compiled for Scala 2.13 still being considered? Or does [this discussion](https://discuss.lightbend.com/t/when-is-there-a-sbt-version-for-2-13/5623) mean this won't happen?

**Comment by eed3si9n** [comment]
I think it would make sense for the next major version of Zinc (named either 1.4.x or 2.x) to be cross built. I have been putting it off since I have a fairly big change that's cooking, and I want to land that first before publishing M1.

**Comment by slandelle** [comment]
Awesome, looking forward to it! Many thanks!

**Comment by lihaoyi** [comment]
I'm also waiting on this to update Mill to Scala 2.13. We could probably work around needing a 2.13 version of Zinc via classloader hackery, but it would be much easier if Zinc supported 2.13 out of the box

**Comment by eed3si9n** [comment]
The fairly big change I was talking about has mostly landed, so I'll try to get something out.

**Comment by eed3si9n** [comment]
Actually if you folks are using this from build tool etc, I might try to cut more conservative tag/branch around https://github.com/sbt/zinc/commit/4353134d78cd858dda60f452397561453c0544bf and cross build there.

**Comment by lihaoyi** [comment]
Thanks @eed3si9n! Either would work for me, I'm not familiar with what commits are in which branch :)

**Comment by lihaoyi** [comment]
Only consideration would be if the newer commit has breaking changes in the API, then I would prefer the older one (or both, so I can upgrade piecemeal)

**Comment by eed3si9n** [comment]
https://github.com/sbt/zinc/releases/tag/v1.4.0-M1 is out.

**Comment by slandelle** [comment]
Thanks a lot @eed3si9n !
