### ISSUE TITLE
Make Analysis machine-independent

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#707]
Current data structure depends too much on the notion of `java.io.File`.
For Zinc 1.4, I propose we get rid of this notion and abstract it as a virtual file.

There are various benefits:
- Reduced file size and memory footprint of Analysis data structure. Currently it's full of absolute path that we have to pass around. 
- Repeatable build.
- Cached compilation.

There has been multiple efforts around build caching, and the technique we have been using is mapping the Analysis (Pants, hoarder, etc). We could skip this process if Analysis was machine-independent to begin with.

**Comment by eed3si9n** [comment]
Here are some of the places absolute paths show up in Analysis.

- output directories:
  /Users/eed3si9n/work/zinc-example/target/scala-2.13/classes -> /Users/eed3si9n/work/zinc-example/target/scala-2.13/classes
- compile options:
   if you're using a compiler plugin
- products:
   /Users/eed3si9n/work/zinc-example/A.scala -> /Users/eed3si9n/work/zinc-example/target/scala-2.13/classes/example/A.class
- library dependencies:
   /Users/eed3si9n/work/zinc-example/A.scala -> /Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar
- library class names:
   /Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar -> scala.Double
- class names:
   /Users/eed3si9n/work/zinc-example/A.scala -> example.A
- product stamps:
   /Users/eed3si9n/work/zinc-example/target/scala-2.13/classes/example/A.class -> lastModified(1570612544091)
- source stamps:
   /Users/eed3si9n/work/zinc-example/A.scala -> hash(4abc48814488f0dd485c6b2daf54b041811e2f41)
- binary stamps:
   /Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar -> lastModified(1568797179000)
- source infos:
    /Users/eed3si9n/work/zinc-example/A.scala -> 
AAAAAAAAAAAAAAAA

**Comment by retronym** [comment]
What's the proposal?

As a straw man, when writing this file, the build tool could provide a map Path Variables (e.g. `Map("COURSIER_CACHE" -> "/Users/eed3si9n/.coursier/cache/v1/", "CLASSES" -> "/Users/eed3si9n/work/zinc-example/target/scala-2.13/classes")`, which would end up writing `${COURSIER_CACHE}/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar`  to the output format. The reader would need to provide the same set of path variables.

**Comment by eed3si9n** [comment]
For sources and `*.class` files the build tool can specify paths relative to the build's base directory.

For JARs, maybe Zinc can provide an automatic way of coming up with unique mapping among the provided list of absolute paths. For example:

```
binary stamps:
2 items
/Users/eed3si9n/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.1/scala-library-2.13.1.jar -> lastModified(1568797179000)
/Users/eed3si9n/.sdkman/candidates/java/8.0.222.hs-adpt/jre/lib/rt.jar -> lastModified(1563351271000)
```

Given these two files, we can use the file name `scala-library-2.13.1.jar` and `rt.jar` as the unique string. If there are two files named `foo-1.0.0.jar`, then we can go up the directory levels until it becomes unique.

So it would look like:

```scala
def generateMapping(classpathJars: Seq[File]): (Seq[String], Map[String, File])
```

As long as different machines map to the same `Seq[String]` we're good.

**Comment by eed3si9n** [comment]
Here's step 1. Output directories field will now have a dummy value - https://github.com/sbt/zinc/pull/708

**Comment by jvican** [comment]
>Reduced file size and memory footprint of Analysis data structure. Currently it's full of absolute path that we have to pass around.
  
We currently compress the analysis in a zip file so the presence of these paths don't make a difference in disk space. Did you mean something else? 

> Repeatable build.

How would a machine-independent analysis help build reproducibility? Build reproducibility is usually considered in the context of one machine. Maybe you meant it in the context of several ones, which would be also related to your point about build caching?
  
All in all, I'm all for making it easier to produce machine-independent analysis files, though I think we should not change the way the Zinc analysis is stored.

For example, I like @retronym's idea of providing a default implementation of the mappers in Zinc that would be customisable by the user. It's a pragmatic solution that brings us the best bang for the buck. 
  
I'm less convinced we should let Zinc pick the unique paths for JARs. It's inherently difficult to find a unique key as that requires to interpret the path with some specific semantics. As JARs can be located anywhere in the file system, I think it's best to let the build tool to decide how should be the paths made machine-independent. By default, we can provide paths for `COURSIER_CACHE` and `IVY_CACHE` or put the values inherited from the environment variables if present. Anything outside there is up to the user/build tool to manage.

**Comment by eed3si9n** [comment]
@jvican 

> We currently compress the analysis in a zip file so the presence of these paths don't make a difference in disk space. Did you mean something else?

There are multiple places where this would show up.
1. Most impactful, I think would be the just the runtime memory usage. The more subprojects we want to load during the compilation the more `java.io.File` there will be full of machine-specific absolute paths. If we can make them intern-able that would allow smaller Analysis, and use memory budget for other things.
2. Even if we zip things, zipping and unzipping hundreds of MB adds time. 

> How would a machine-independent analysis help build reproducibility? Build reproducibility is usually considered in the context of one machine. Maybe you meant it in the context of several ones, which would be also related to your point about build caching?

Yes, my concern is organization-wide and global build reproducibility. The fact that the jar becomes identical would be a good milestone on its own to have. (We should find out if that's not the case) Once we have that, caching becomes more reliable across build machines etc.

**Comment by jvican** [comment]
> The more subprojects we want to load during the compilation the more java.io.File there will be full of machine-specific absolute paths. If we can make them intern-able that would allow smaller Analysis, and use memory budget for other things.
  
I agree, this is an inherent problem with `java.io.File`. If we were using `java.nio.file.Path`, the paths would be interned by default. However, I'm not sure the before/after situation with shortening paths makes a big difference. In the scenario where shortened paths are used, Zinc needs to resolve the shortened paths to fully qualified paths in memory to make sense of them. When they are resolved, they occupy the same memory profile as before. If anything, this should be more inefficient than loading the right paths from memory as the resolution step creates a bigger memory profile.
  
Aside from the performance considerations, I believe it makes sense to provide default mappers in Zinc and I'm looking forward to an implementation :+1:

**Comment by retronym** [comment]
> Zinc needs to resolve the shortened paths to fully qualified paths in memory to make sense of them. 

However, that need only be done one-at-a-time with a temporary `File` or `Path` object with the fully qualified name.

**Comment by jvican** [comment]
> However, that need only be done one-at-a-time with a temporary File or Path object with the fully qualified name.
  
I was considering the situation where the translation between shortened paths and fully qualified paths is done once. Do you mean that as well or that we can make the resolution lazy?

**Comment by retronym** [comment]
> I was considering the situation where the translation between shortened paths and fully qualified paths is done once. Do you mean that as well or that we can make the resolution lazy?

I was thinking of a scheme where the fully qualified path resolution was done on-demand, temporarily, and any long-lived representations in memory would represent things as proposed for the on-disk format. 

I guess we need some more data to drive the decision about how much interning alone helps.

**Comment by eed3si9n** [comment]
Another benefit of even attempting to replace `java.io.File` to a `VirtualFile` is that we can smoke out all the locations that we are doing IO operations using it. Even if we ultimately keep `java.io.File` as the String holder, it would be useful to know where we can potentially optimize on IO.

This is more on Java compilation side, but for example there's some funky stuff happening in https://github.com/sbt/zinc/blob/v1.3.1/internal/zinc-classfile/src/main/scala/sbt/internal/inc/classfile/Analyze.scala#L272-L320

**Comment by eed3si9n** [comment]
A point brought up by @pnf was that we throw out rich metadata about the metadata of JAR files.

For machine-independent mapping, it might be useful to recapture `ModuleID` information like organization, artifact name, and version instead of the path that your dependency resolver happened to store your JARs. This could have implication in corporate environments where Maven artifacts are often mapped as files on a shared drive. (I've seen that on multiple organizations)

**Comment by jvican** [comment]
> I guess we need some more data to drive the decision about how much interning alone helps.
  
@retronym This would be helpful, it looks like we don't have a clear idea of what the performance foot print of the status quo is. If this ticket keeps framed in the context of performance, some numbers would help us make a more informed decision.

@eed3si9n Those are good points and could be addressed with `java.nio.file.Path` and `java.nio.file.FileSystem`. Why don't we migrate Zinc away from `java.io.File` to `java.nio.file.Path`? It seems like the most solid solution for the future of Zinc and seems to check all of the boxes.

**Comment by eed3si9n** [comment]
![vf](https://user-images.githubusercontent.com/184683/67526266-6f009000-f682-11e9-8ae5-942f4e70435d.png)

I don't have the full picture yet until I am done prototyping, but we need different degree of power from what we today call "File". The diagram above shows the two inputs going into Zinc compilation:

- Array of files
- Previous Analysis file

### how files are used

- The current hypothesis is that thawed back Analysis file only needs `Eq`, the ability to distinguish one from the other. I am calling that `VirtualFileRef`.
- The opposite end of spectrum is `javac` integration. For that we need `java.io.File`, but that's ok because like I said we have it as input parameter.
- Scala compiler sits somewhere in the middle. It has a virtual file like trait `scala.reflect.io.AbstractFile`, but it seems too featureful. I am hoping that it just needs the ability to read the content of the source. 

Once the compilation starts,  the compiler is going to report back compilation errors etc, so we need a way to encode back the `VirutalFile` back to the local `java.io.File` / NIO Path, so it could try different different encoding technique.

The memory part that I'm hoping to reduce is the thawed back Analysis. In order to incrementally compile a subproject Foo, we (currently) need to load in all dependency subproject's Analysis into memory.

**Comment by smarter** [comment]
> Those are good points and could be addressed with java.nio.file.Path and java.nio.file.FileSystem. Why don't we migrate Zinc away from java.io.File to java.nio.file.Path?

+1000 to this. Once we move scalac and dotty to NIO and get rid of AbstractFile this will make it possible to have a shared concept of virtual files (e.g. using https://github.com/google/jimfs) that both the compiler and zinc understand. Using NIO also seems to be necessary for properly handling incremental compilation using the java 9+ modulepath instead of the classpath: https://github.com/lampepfl/dotty/blob/1d5e6edd564748c4cedc6893fcd9aeca13bedef4/compiler/src/dotty/tools/dotc/sbt/ExtractDependencies.scala#L132-L137

**Comment by pnf** [comment]
Why do we want a representation that has anything to do with paths or files? In addition to having unnecessary methods, nio.Path also lacks meaningful stamp equality. The ideal representation of any external dependency is exactly what we use to resolve against external repositories, and stamp equality is trivially the concatenation of those fields, including version. 
Local dependencies are not conceptually different except in that we don’t usually bother to give them versions - a reasonable one would be a hash derived from source text together with upstream versions. 
The way we know that an analysis representation is sufficiently workspace-independent is that it could itself be fetched from a repository.

**Comment by eed3si9n** [comment]
There are severals kinds of files we deal with and they are all called files.

1. Scala sources
2. Java sources
3. `*.class` "products" (or `*.jar` in case of compile-to-JAR)
4. `*.jar` library files

For source code, https://github.com/sbt/zinc/pull/712 replaces the reference to them as `VirtualFileRef` while keeping the input as `VirtualFile` that can turn into NIO Path.

`*.class` products might need IO operations because of the TransactionalClassFileManager https://github.com/sbt/zinc/blob/v1.3.1/internal/zinc-core/src/main/scala/sbt/internal/inc/ClassFileManager.scala#L133. This vacates the class files generated by the Scala sources in the _previous_ round of compilation. Since this is a previous knowledge, I need to store that in Analysis. Thankfully `*.class` files are something that are generated under output directory (or into JAR) so we can pick some naming convention like `${out}foo/bar/A.class`.

I haven't gotten to `*.jar` yet, but hopefully it would be similar to source code give and take `ModuleID` metadata.

As per the compiler internals, I think it would be a useful exercise to come up with the minimum subset of [`scala.reflect.io.AbstractFile`](https://github.com/scala/scala/blob/v2.13.1/src/reflect/scala/reflect/io/AbstractFile.scala) that is needed to scan `*.scala` and `*.java` files. Both `scala.reflect.io.AbstractFile` and NIO Path conflate the ability to read content with the ability to act as a directory-based filesystem by implementing an iterator of itself and requiring `getParent` (or `container`).

**Comment by pnf** [comment]
And .sig I guess, in the same sense as .class. 
But the analysis format doesn’t have to be aware of the fact that something originated as a file or can be turned into or inserted into one. For clarity, the classes used to store these abstract references ideally wouldn’t even have File in their names. 
On the other hand, they would contain the sort of metadata necessary to assert equality. Together with the provenance id in AnalyzedClass (apparently I’m allowed to contribute that now, but please direct questions to my @pnfms alter-ego), we can not only achieve workspace independence but determine from an AC and the compilation class path whether it’s necessary to crack open the upstream analyses in the first place.

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/zinc/pull/712 and other PRs hopefully.
