### ISSUE TITLE
Remove support for resident compiler

### ISSUE THREAD

**Issue by lrytz** [sbt/zinc#711]
https://github.com/sbt/zinc/commit/e852092dd added support for keeping compiler instances in memory and re-using them for incremental compilations.

Using the Scala compiler in "resident" mode means keeping a `nsc.Global` instance alive and only creating a new `global.Run` for compiling a set of sources. The symbol table is kept between runs, which is supposed to improve performance (no need to re-parse classfiles from the classpath). This is used in the REPL, in (deprecated/discouraged) `fsc`, and by the presentation compiler (Scala IDE for Eclipse, Ensime, REPL-completions). Using `-Dsbt.resident.limit=n` enables the resident compiler in sbt.

While the incremental compiler became pretty robust over the years, there are still risks to using it in sbt:
  - Risk for memory leaks
  - Bugs in the presentation compiler affect the compilation result, which seems more significant than issues in the presentation compiler or REPL

Intuitively, the performance advantage of the resident compiler is most significant when compiling a small body of code, like in the REPL or presentation compiler. In these interactive scenarios, a really quick feedback is very important, so the time for initializing the `Global` instance is probably relevant. In ordinary compilation, adding a constant second or two is much less releavant.

Note that the main speedup of the Scala compiler in sbt (compared to invoking `scalac` on the command line) is due to the JVM continuing to run, which keeps the JIT-compiled compiler available. Creating and running a new `Global` in an already warmed-up JVM is a lot faster than creating a new `scalac` JVM process. This is how sbt works by default.

https://github.com/sbt/zinc/issues/340 is an existing ticket about removing resident mode from zinc, but it was not actually done (https://github.com/sbt/zinc/blob/develop/internal/compiler-interface/src/main/java/xsbti/compile/CachedCompiler.java is still there). In the SO answer linked on the ticket, Grzegorz says

> Our findings showed us that the improvements to speed were not as large as we expected. The complexity of resident compilation is really large due to issues like memory leaks or sound symbol table invalidation.

I propose to remove support for resident compilation from zinc.

The reason I bring up this topic is that I'm working with @eed3si9n on integrating the compiler bridge into the Scala compiler, similar to what dotty does. It seems to be a good moment to simplify the compiler inteface during that process. I would like to keep the discussion here focused on the resident compilation question, I'll open other tickets for discussing the change to the compiler bridge (https://github.com/sbt/zinc/issues/78 has some older discussion).

cc @jvican, @retronym

**Comment by eed3si9n** [comment]
> In ordinary compilation, adding a constant second or two is much less relevant.

Zinc gets called in a various situations. For example, sbt user might be continuously testing something using `~testOnly foo.bar`. In those situations, seeing tests start a few seconds quicker does add to an improvement of overall responsiveness, and we've done things like ClassLoader layering to do so.

If we don't use the code path because of correctness concerns, I am all for removing the interface etc, but I wonder if there might be a way to save it. For example, could sbt jump start a fresh `Global` in-memory in anticipation of `compile` during idle?

**Comment by jvican** [comment]
> I propose to remove support for resident compilation from zinc.
  
I'd like to keep resident compilation support in Zinc.

I have use cases for it in bloop where resident compilation is still important, for example when compiling code snippets whose classpath is always the same. Compiling a small code snippet with resident compilation enabled can be done in 10ms while with a new global instance it takes around 180ms.

**Comment by lrytz** [comment]
> In those situations, seeing tests start a few seconds quicker does add to an improvement of overall responsiveness

Right, I agree. Note that I didn't measure or even try out the difference; it seems Grzegorz did at some point.

> we've done things like ClassLoader layering to do so

Is that https://github.com/sbt/sbt/pull/2754 / https://github.com/sbt/zinc/pull/196 ?

> could sbt jump start a fresh `Global` in-memory in anticipation of `compile` during idle?

That's an idea, but I think there is not much to be gained. The instantiation of `Global` is really quick, try `new scala.tools.nsc.Global(new scala.tools.nsc.Settings)` in the REPL. I assume the main advantage of the resident compiler (i.e., keeping `Global` and creating a new `Run`) is that the symbol table does not need to be re-created from scratch. However, the type of every symbol that is re-used goes through the `adaptToNewRunMap`, it's not completely free either.

**Comment by lrytz** [comment]
> compiling code snippets whose classpath is always the same

Can you expand a little, is that for IDE support?

**Comment by eed3si9n** [comment]
@lrytz ClassLoader layering for `test` was done in https://github.com/sbt/sbt/pull/4476

**Comment by jvican** [comment]
> Can you expand a little, is that for IDE support?
  
Yes, for worksheets and notebooks. For example, we can use resident compilation to compile Ammonite expressions and refresh the resident compiler whenever the user loads a library that changes the classpath.

**Comment by lrytz** [comment]
OK, thanks. I guess I have to add bloop to the list of sources that I need to look at :-) Is there some higher level description already somewhere?

**Comment by retronym** [comment]
Related: https://github.com/scalacenter/bloop/issues/31   https://github.com/scala/compiler-benchmark/pull/39

**Comment by lrytz** [comment]
Closing, as support for resident compilation will most likely stay. It can be useful for repl-like use cases, of which bloop seems to have one.
