### ISSUE TITLE
Allow operation without a filesystem

### ISSUE THREAD

**Issue by stephenjudkins** [sbt/zinc#717]
Currently, input and output files are specified in the API in terms of `java.io.File`. The underlying Scala compiler, however, does not require interaction with the filesystem. If inputs and outputs could be handled through in-memory data structures it could open the door for some optimizations in some cases (in this case, in the https://github.com/higherkindness/rules_scala project).

I'm aware this is a large issue, but figured I'd open it to signal support.

**Comment by eed3si9n** [comment]
@stephenjudkins Thanks. I am sort of working on this here - https://github.com/sbt/zinc/pull/712

**Comment by stephenjudkins** [comment]
This is wonderful, I'm glad to know it's being worked on.

**Comment by eed3si9n** [comment]
@stephenjudkins I now have tests passing with in-memory source code.
I don't know how difficult it would be to abstract the JAR files, but I feel like I should just allow JAR files to be.

**Comment by Friendseeker** [comment]
I assume Zinc's current virtual file system counts as "Allow operation without a filesystem". If Zinc's current implementation is not good enough, we can revisit the issue later.
