### ISSUE TITLE
DelegatingReporter.scala:171: warning: match may not be exhaustive

### ISSUE THREAD

**Issue by pzygielo** [sbt/zinc#730]
When used with scala-maven-plugin, following is logged:
```
[INFO] --- scala-maven-plugin:4.3.1:compile (scala-compile-first) @ scala ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiler bridge file: .../.sbt/1.0/zinc/org.scala-sbt/org.scala-sbt-compiler-bridge_2.13-1.3.2-bin_2.13.1__52.0-1.3.2_20200115T025827.jar
[INFO] Compiler bridge file is not installed yet
Downloading from ... .../org/scala-sbt/compiler-bridge_2.13/1.3.2/compiler-bridge_2.13-1.3.2-sources.jar
Downloaded from ... .../org/scala-sbt/compiler-bridge_2.13/1.3.2/compiler-bridge_2.13-1.3.2-sources.jar (49 kB at 142 kB/s)
Downloading from ... .../org/scala-sbt/compiler-bridge_2.13/1.3.2/compiler-bridge_2.13-1.3.2.pom
Downloaded from ... .../org/scala-sbt/compiler-bridge_2.13/1.3.2/compiler-bridge_2.13-1.3.2.pom (2.9 kB at 16 kB/s)
/tmp/scala-maven-plugin-compiler-bridge-sources5143868927709416200/xsbt/DelegatingReporter.scala:171: warning: match may not be exhaustive.
It would fail on the following inputs: ERROR, INFO, Severity(), WARNING
    sev match {
    ^
warning: there were four deprecation warnings (since 2.12.0)
warning: there were four deprecation warnings (since 2.12.5)
warning: there were two deprecation warnings (since 2.12.9)
warning: there were two deprecation warnings (since 2.13)
warning: there were 7 deprecation warnings (since 2.13.0)
warning: there were 19 deprecation warnings in total; re-run with -deprecation for details
warning: there were three feature warnings; re-run with -feature for details
8 warnings found
[INFO] Compiler bridge installed
[INFO] Compiling 1 Scala source to .../target/classes ...
[INFO] Done compiling.
[INFO] compile in 23.6 s
```

**Comment by eed3si9n** [comment]
@pzygielo Thanks for the report!

**Comment by superancientages** [comment]
@eed3si9n @pzygielo Hi! Any tips to solve this issue?
Faced with same warning using Gatling and Scala 2.13.3

**Comment by eed3si9n** [comment]
Here's https://github.com/sbt/sbt/blob/v1.4.7/internal/util-interface/src/main/java/xsbti/Severity.java:

```java
package xsbti;

public enum Severity {
  Info,
  Warn,
  Error
}
```

and if I believe the posted warning:

```
It would fail on the following inputs: ERROR, INFO, Severity(), WARNING
    sev match {
    ^
```

the warning is coming from https://github.com/sbt/zinc/blob/13ddb10938237263f706174439d8ed055e8e4ac2/internal/compiler-bridge/src/main/scala/xsbt/DelegatingReporter.scala#L189-L196 ?

This feels like a Scala compiler bug.

I guess the workaround would be to put `case _ => ...` if someone wants to send a pull request. I'm not sure why scala-maven-plugin and Gatling would hit this but not others.

**Comment by frankbe** [comment]
I got the same error with scala-maven-plugin 4.5.3 and compiler-bridge 1.5.5 on scala 2.13.6

org.scala-sbt-compiler-bridge_2.13-1.5.5-bin_2.13.6__55.0-1.5.5_20210607T021730.jar
DelegatingReporter.scala:191: warning: match may not be exhaustive

**Comment by eed3si9n** [comment]
This was fixed by @dwijnand in https://github.com/sbt/zinc/pull/996

**Comment by frankbe** [comment]
it seems that is was just a cache issue. It didn't come across again since I restarted intellij (with invalidate cache option) twenty minutes ago. Sorry for false alarm. EDIT: it happend direct after an upgrade from scala 2.13.2 to 2.13.6

**Comment by dwijnand** [comment]
> This feels like a Scala compiler bug.

No, the input Severity is the compiler's, such as

https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/reporters/Reporter.scala#L44-L53

**Comment by pzygielo** [comment]
Thank you for fixing this.
