### ISSUE TITLE
Support configurations options in scripted tests

### ISSUE THREAD

**Issue by Duhemm** [sbt/zinc#75]
`scripted` for this project do not support `build.sbt`. We should still have a way to configure the incremental compiler.

How about a simple properties file `options.properties` at the root of the scripted tests ?

```
scalaVersion = 2.11.7
scalacOptions = -sourcepath srcpath
```

**Comment by Duhemm** [comment]
Functionalities that @gkossakowski needs:
- [x] check-compilations -> which files are recompiled at each step

```
> check-recompilations A.scala, B.scala C.scala, D.scala
```

means that we expect `A.scala` to be compiled in step 0, `B.scala` and `C.scala` in step 1, and `D.scala` in step 2.
- [x] check-products -> get all the products for a source

```
> check-products A.scala: classes/A.class classes/A$.class
```

means that we expect that the compilation of `A.scala` generates the classfiles `classes/A.class` and `classes/A$.class`.
- [x] check-dependencies -> who depends on who

```
> check-dependencies A.scala: B.scala C.scala
```

means that we expect `A.scala` to have a source dependency on `B.scala` and `C.scala`.
- [x] support all IncOptions (or at least recompileAllFraction, apiDebug, apiDiffContextSize)
  Note sure what the best syntax would be here.

**Comment by jvican** [comment]
This has already been added a loooong time ago. The file to configure scripted is called `incOptions.properties`.
