### ISSUE TITLE
Further issues with associatedFile 

### ISSUE THREAD

**Issue by retronym** [sbt/zinc#757]
- Scalac does not set `associatedFile` until  a class symbol's info is forced. It is possible to get a reference to type after typechecking that didn't actually need to force it. I've see this in a tree type of `x.getClass.getName`. The `Select(Ident(x), TermName(getClass))` tree had a type `Class[_ <: SomeClass]` where the class symbol for `SomeClass` was unitialized. I'm working on a reproducer, there is some special logic in type for `getClass` so maybe thats irregular?
   - I could set up scalac to return the correct `associatedFile` even before the info is forced.
 - When Zinc traverses the `original` of ` TypeTree` we an have an `Ident` with a `tpe` assigned but _no_ `.symbol` assigned. Again, I'm working on a reproducer, this might be related to case class accessor synthesis. This searches the classpath for the FQN of `<none>`.
 - .. which it incorrectly computes as `<none>xxxxxxxx`, where the `xxx` is whatever characters are adjacent to `<none>` in the name table. This is due to a bug in `CallbackGlobal.fullName` which computes string lengths of `symName.encoded` but then discards the encoded name and takes data from the name table starting at `symName.start`.
 - Other special symbols like `<byname>` / `<repeated>` and `scala.Nothing` are also looked for on the classpath. This could be fixed by a) first checking for `definitions.isPhantomClass | defintions.syntheticCoreClasses`; b) caching negative lookups or c) both.

**Comment by retronym** [comment]
Following on from from #559

**Comment by eed3si9n** [comment]
I noticed this on sbt CI running on  AppVeyor https://ci.appveyor.com/project/sbt/sbt/builds/32292313

```
C:\Users\appveyor\AppData\Local\Temp\1\sbt_698f07ee\project\target\scala-2.12\sbt-1.0\classes
[info] [error] java.nio.file.InvalidPathException: Illegal char <<> at index 6: scala/<repeated>_*$treecrea.class
[info] [error] sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[info] [error] sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[info] [error] sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[info] [error] sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
[info] [error] sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
[info] [error] sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
[info] [error] xsbt.ZincCompiler.$anonfun$findAssociatedFile$1(CallbackGlobal.scala:175)
[info] [error] scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
[info] [error] scala.collection.immutable.List.foreach(List.scala:392)
[info] [error] scala.collection.TraversableLike.map(TraversableLike.scala:273)
[info] [error] scala.collection.TraversableLike.map$(TraversableLike.scala:266)
[info] [error] scala.collection.immutable.List.map(List.scala:298)
[info] [error] xsbt.ZincCompiler.findOnPreviousCompilationProducts$1(CallbackGlobal.scala:175)
[info] [error] xsbt.ZincCompiler.$anonfun$findAssociatedFile$5(CallbackGlobal.scala:185)
[info] [error] scala.Option.orElse(Option.scala:447)
[info] [error] xsbt.ZincCompiler.findAssociatedFile(CallbackGlobal.scala:184)
[info] [error] xsbt.Dependency$DependencyProcessor.processDependency(Dependency.scala:168)
[info] [error] xsbt.Dependency$DependencyProcessor.$anonfun$memberRef$1(Dependency.scala:101)
[info] [error] xsbt.Dependency$DependencyProcessor.$anonfun$memberRef$1$adapted(Dependency.scala:101)
```

Maybe we should run Zinc CI on AppVeyor as well?
