### ISSUE TITLE
[1.4.0-M2] ??? not implemented code in IncrementalCompilerImpl

### ISSUE THREAD

**Issue by slandelle** [sbt/zinc#761]
Not sure if this is intended, a wip or something missing, but as of 1.4.0-M2 (no git tag) IncrementalCompilerImpl can crash because there's a `converter.getOrElse(???)` line 56: https://github.com/sbt/zinc/blob/develop/zinc/src/main/scala/sbt/internal/inc/IncrementalCompilerImpl.scala#L56

**Comment by eed3si9n** [comment]
@slandelle Thanks for the report. Unlike M1 that's similar to 1.3.x, M2 is still raw. Good catch though :)

**Comment by slandelle** [comment]
@eed3si9n Noted, thanks.

FYI, I stumbled on this because I was using the `CompileOptions.of` overload that sets `_converter` as `Optional.empty`.

**Comment by eed3si9n** [comment]
Here's PR for this - https://github.com/sbt/zinc/pull/877
