### ISSUE TITLE
[1.4.x] Presenting source files as VirtualFileWrap prevents memory efficient code path in scalac's SourceReader

### ISSUE THREAD

**Issue by retronym** [sbt/zinc#770]
https://github.com/sbt/zinc/blob/db028c338af528876e24fc8d6214e24f7d19d707/internal/compiler-bridge/src/main/scala/xsbt/CompilerInterface.scala#L156-L160

Seems to stop use getting to the efficient first line in:

https://github.com/scala/scala/blob/2826c6cb96f948cbe1c90ca73e43c8aa399fa1a9/src/compiler/scala/tools/nsc/io/SourceReader.scala#L58-L63

Which leads to allocation profiles like:

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/65551/80711124-33fc7f00-8b33-11ea-82e9-36ff3ed9f75d.png">

**Comment by retronym** [comment]
@eed3si9n What's the rationale behind the wrapping? Is fixing this as easy as making a more fine-grained conversion, that e.g. converts `sbt.internal.inc.PlainVirtualFile` into `scala.reflect.io.PlainFile`?

**Comment by eed3si9n** [comment]
> What's the rationale behind the wrapping?

`xsbti.VirtualFile` lives in the compiler interface, which doesn't depend on almost anything else whereas `scala.reflect.io.AbstractFile` is specific to an implementation of Scalac. `VirtualFileWrap` bridges between those two worlds - https://github.com/sbt/zinc/blob/develop/internal/compiler-bridge/src/main/scala/xsbt/VirtualFileWrap.scala. The success criteria for `VirtualFile` is that it supports in-memory source file.

> Is fixing this as easy as making a more fine-grained conversion, that e.g. converts `sbt.internal.inc.PlainVirtualFile` into `scala.reflect.io.PlainFile`?

That might not work because Zinc's added phases + callback for things like API extraction and error reporting would be expecting a `VirtualFile` reference. What we might need is a cooperation with the compiler and use faster IO only for content reading?

**Comment by retronym** [comment]
An alternative would be that Zinc could maintain an `IdentityHashMap[AbstractFile, VirtualFile]` and used that to convert compiler source files back into Zinc `VirtualFiles`.

**Comment by retronym** [comment]
Relatedly, I notice that Zinc internal threads the sources through as a `Set[VirtualFile]`. It orders these deterministically into a `Seq` before passing them to scalac, but Zinc's operations themselves operate on the `Set`.

I'm not sure what sort of `Set` this is in practice. If its a `HashSet`, this opens up SBT's behaviour to be non-deterministic. Even if the results of SBT don't change when it does its analysis in different processing order, it can be useful for debugging if successive runs to do things in the same order. 

So maybe it would be worth to introduce an internal class to encapsulate a set of source files. It would deduplicate and order by id on construction, store the mapping between `VirtualFile` and `AbstractFile` (avoiding the need to `VirtualFileWrap` for standard types of file.

**Comment by retronym** [comment]
Here's a compensating change which could go into 2.12.12: https://github.com/scala/scala/pull/8944

I think its still worth considering presenting `PlainFile` to the compiler for sources though.

**Comment by eed3si9n** [comment]
> I think its still worth considering presenting `PlainFile` to the compiler for sources though.

Yea. I agree it makes sense to avoid perf regressions on existing Scala versions.

**Comment by eed3si9n** [comment]
@adpi2 Maybe this discussion may be helpful. If you want to implement the mapping proposed by Jason, you could minimize the usage VirtualFileWrap, and the downstream tooling like scalameta would mostly see PlainFile like before?
