### ISSUE TITLE
Reduce memory of Zinc by de-duplicating Strings, etc

### ISSUE THREAD

**Issue by retronym** [sbt/zinc#780]
Using Java Mission control, take a heap dump of a running SBT build. The resulting UI includes the JOverflow analysis of opportunities to reduce footprint.

`ClassLike.savedAnnotations` contains duplicate strings for `scala.native` `scala.deprecated` etc.

<img width="948" alt="image" src="https://user-images.githubusercontent.com/65551/81243054-14dd8000-9052-11ea-8b3d-babd31811174.png">

`UsedName` / `NameHash`

<img width="1929" alt="image" src="https://user-images.githubusercontent.com/65551/81243138-5706c180-9052-11ea-88ef-3c922c2fa7d7.png">

My work on `RelationsBuilder` in https://github.com/sbt/zinc/pull/764 is a step in the right direction.

Related fix for SBT itself: https://github.com/sbt/sbt/pull/5535

**Comment by Friendseeker** [comment]
Closed by #1326
