### ISSUE TITLE
Zinc API (Java API)

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#79]
Java API (
https://github.com/sbt/zinc/blob/1.0/internal/compiler-interface/src/main/java/xsbti/compile/IncrementalCompiler.java) should be able invoke incremental compilation from soup to nuts like - https://github.com/sbt/zinc/blob/1.0/incrementalcompiler/src/test/scala/sbt/inc/IncrementalCompilerSpec.scala

**Comment by javeleon** [comment]
migrating comments from duplicate issue #126.

Currently, I find it extremely hard to setup Zinc for incremental compilation, especially from Java.

I was pointed to this example for setting up Zinc: https://github.com/sbt/zinc/blob/1.0/zinc/src/test/scala/sbt/inc/IncrementalCompilerSpec.scala

The first problem I have is that there while IncrementalCompilerUtil.defaultIncrementalCompiler() has return type IncrementalCompiler (which is fine) the IncrementalCompiler interface has no useful methods to create a compiler for Java sources.

Second problem is that while the IncrementalCompiler interface does provide a method for compiling (compile) it does so by means of param type 'Inputs'. That in turn drives me to the internal implementation class IncrementalCompilerImpl which I really don't want to know anything about. Trying to fill in all the blanks here utilizing, in examples the inputs(), setup() and compilers methods, drives me nuts, and I finally gave up trying to make it work.

There should really be a simple API for all of this, perhaps even something similar to that of what Zinc originally provided in the Typesafe repos.

Ideally, you would provide something that would allow easy setup for Java-only mode also, but that's not a hard requirement.

**Comment by jvican** [comment]
We're covering this one here -> https://github.com/sbt/zinc/issues/300.
  
Closing.
