### ISSUE TITLE
sbt-datatype doesn't allow docs

### ISSUE THREAD

**Issue by gkossakowski** [sbt/zinc#81]
The JSON format sbt-datatype uses doesn't have a place to stick in docs (JSON doesn't allow comments). I've run into this problem while working on `DependencyContext`. It looks like this in sbt 0.13:

``` java
package xsbti;

/**
 * Enumeration of existing dependency contexts.
 * Dependency contexts represent the various kind of dependencies that
 * can exist between symbols.
 */
public enum DependencyContext {
    /**
     * Represents a direct dependency between two symbols :
     * object Foo
     * object Bar { def foo = Foo }
     */
    DependencyByMemberRef,

    /**
     * Represents an inheritance dependency between two symbols :
     * class A
     * class B extends A
     */
    DependencyByInheritance,
    /**
     * Represents an inheritance dependency between a local class
     * and a non local class:
     *
     *   // A.scala
     *   class A
     *   // B.scala
     *   class B {
     *     def foo = {
     *       class Local extends A
     *     }
     *   }
     */
    LocalDependencyByInheritance
}
```

in zinc, its definition is:

```
{
  "name": "DependencyContext",
  "namespace": "xsbti.api",
  "target": "Java",
  "type": "enumeration",
  "types": [
    "DependencyByMemberRef",
    "DependencyByInheritance",
    "LocalDependencyByInheritance"
  ]
},
```

The lacks of docs is great loss.

**Comment by gkossakowski** [comment]
@eed3si9n, @Duhemm: what was the reason to move away from hand written enum for DependencyContext?

**Comment by Duhemm** [comment]
@gkossakowski You can add documentation in the JSON: https://github.com/sbt/sbt-datatype/blob/master/library/src/main/scala/SchemaData.scala#L153-L195

They appear in the code generated: https://github.com/sbt/sbt-datatype/blob/master/library/src/test/scala/JavaCodeGenSpec.scala#L10-L21

The reason to move was (I think) to be coherent and use sbt-datatype for all the publicly available structures of the incremental compiler.

**Comment by gkossakowski** [comment]
Thanks for the pointer. I tried using the "doc" element but ran into two issues:
1. You can't have multineline strings in JSON so my docs on LocalDependencyByInheritance have to be written as
   `/**\n * Represents an inheritance dependency between a local class\n * and a non local class:\n *\n *   // A.scala\n *   class A\n *   // B.scala\n *   class B {\n *     def foo = {\n *       class Local extends A\n *     }\n *   }\n */`, which is an unreadable mess
2. You cannot put a doc comment on individual elements of an enum

**Comment by Duhemm** [comment]
@gkossakowski I remember writing documentation for sbt-datatype. It should be up-to-date: http://www.scala-sbt.org/0.13/docs/Datatype.html
1. We circumvent this problem by using arrays: https://github.com/sbt/sbt-datatype/blob/master/library/src/test/scala/SchemaExample.scala#L201-L204
2. You can: Schema: https://github.com/sbt/sbt-datatype/blob/master/library/src/test/scala/SchemaExample.scala#L112-L124 Code that gets generated: https://github.com/sbt/sbt-datatype/blob/master/library/src/test/scala/JavaCodeGenSpec.scala#L10-L21

**Comment by Duhemm** [comment]
The definition of DependencyContext could be rewritten as:

``` json
{
  "name": "DependencyContext",
  "doc": [
    "Enumeration of existing dependency contexts.",
    "Dependency contexts represent the various kind of dependencies that",
    "can exist between symbols."
  ],
  "namespace": "xsbti.api",
  "target": "Java",
  "type": "enumeration",
  "types": [
    {
      "name": "DependencyByMemberRef",
      "doc": [
        "Represents a direct dependency between two symbols :",
        "object Foo",
        "object Bar { def foo = Foo }",
      ]
    },
    {
      "name": "DependencyByInheritance",
      "doc": [
        "Represents an inheritance dependency between two symbols :",
        "class A",
        "class B extends A"
      ]
    },
    {
      "name": "LocalDependencyByInheritance",
      "doc": [
        "Represents an inheritance dependency between a local class",
        "and a non local class:",
        "  // A.scala",
        "  class A",
        "  // B.scala",
        "  class B {",
        "    def foo = {",
        "      class Local extends A",
        "    }",
        "  }"
      ]
    }
  ]
}
```

This should give something very similar to the code that you sent above (modulo my typos).

**Comment by gkossakowski** [comment]
Ok, thanks. I've added the documentation of DependencyContext to json file.
