### ISSUE TITLE
false-positives "Detected a change in a public API" 

### ISSUE THREAD

**Issue by jtjeferreira** [sbt/zinc#810]
Coming from https://github.com/sbt/sbt/issues/5570#issuecomment-653599363 I also see a lot of messages like the the original poster reported

```
[debug]The com.nezasa.model.iam.User has the following regular definitions changed:
[debug]         UsedName(failsInventoryOwnerCheck,[Default]).
```

In my work project, right now this is the only change that I now have in the logs, but in previous sessions I noticed others...

Running `compile` multiple times without changing any source files always triggers this message, and If I enable better logs with `incOptions ~= (o => o.withApiDebug(true).withRelationsDebug(true)),` I can see:

```
[debug] [diff] Detected a change in a public API (com.nezasa.model.iam.User):
[debug] [diff] @scala.this#SerialVersionUID(value = 1006L) class com.nezasa.model.iam.User extends scala.this#Serializable with java.io.this#Serializable with scala.this#Product with scala.this#Equals with com.nezasa.comms.this#Logging with com.nezasa.model.iam.this#EmailRecipient with com.nezasa.model.serialization.this#NezasaModelObject with com.nezasa.model.serialization.this#NezasaModelCOObject with com.nezasa.model.serialization.this#NezasaModelTOObject with com.mohiva.play.silhouette.api.this#Identity with java.lang.this#Object with scala.this#Any {
[debug] [diff] 
[debug] [diff] 
[debug] [diff] 
[debug] [diff] }
[debug] [diff] object com.nezasa.model.iam.User extends scala.this#Serializable with java.io.this#Serializable with com.nezasa.model.iam.this#UserDatabase with com.nezasa.dao.utils.this#DaoAdapter[com.nezasa.dao.this#UserDao] with com.nezasa.comms.this#Logging with com.nezasa.model.serialization.this#NezasaModelCompanion[com.nezasa.model.iam.this#User, com.nezasa.model.iam.this#UserTO] with java.lang.this#Object with scala.this#Any {
[debug] [diff] 
[debug] [diff] 
[debug] [diff] 
[debug] [diff] }
[debug] The com.nezasa.model.iam.User has the following regular definitions changed:
[debug]         UsedName(failsInventoryOwnerCheck,[Default]).
[debug] All member reference dependencies will be considered within this context.
[debug] Files invalidated by inheriting from (external) com.nezasa.model.iam.User: Set(); now invalidating by inheritance (internally).
[debug] Getting direct dependencies of all classes transitively invalidated by inheritance.
[debug] Getting classes that directly depend on (external) com.nezasa.model.iam.User.
[debug] None of the modified names appears in source file of controllers.location.api.AirportsApiController. This dependency is not being considered for invalidation.
[debug] None of the modified names appears in source file of controllers.location.api.AreasApiController. This dependency is not being considered for invalidation.
[debug] No changes
```

However I dont understand what that diff represents...

Something that I also noted is that this is a multimodule project and although this `User` class is used pervasively in all the modules only a single module is showing this message...

**Comment by jtjeferreira** [comment]
A simpler case 

```
[trip-builder] $ wikivoyage/compile
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Copy resource mappings: 
[debug] 	
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 4 products, 1 sources, 5 libraries Map(${BASE}/modules/utils/throttling/src/main/scala/com/nezasa/utils/throttling/ThrottlingSupport.scala -> farm(f1f24a0b136e5c93))
[debug] current source = Set(${BASE}/modules/utils/throttling/src/main/scala/com/nezasa/utils/throttling/ThrottlingSupport.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] No changes
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 50 products, 5 sources, 16 libraries Map(${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/wikimarkupparser/package.scala -> farm(26929d773db886f0), ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/WikivoyageClient.scala -> farm(f26e61a1b7c3c1bc), ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/model/package.scala -> farm(b52d3341a989253a), ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/WikiVoyageArticleParser.scala -> farm(db0bb890f85cc214), ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/wikimarkupparser/WikimarkupParserBase.scala -> farm(2ef1f3e822b88d02))
[debug] current source = Set(${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/wikimarkupparser/package.scala, ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/WikivoyageClient.scala, ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/model/package.scala, ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/WikiVoyageArticleParser.scala, ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/wikimarkupparser/WikimarkupParserBase.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set(NamesChange(com.nezasa.utils.throttling.ThrottlingSupport$,ModifiedNames(changes = UsedName(logger,[Default])))))
[debug] The com.nezasa.utils.throttling.ThrottlingSupport$ has the following regular definitions changed:
[debug] 	UsedName(logger,[Default]).
[debug] All member reference dependencies will be considered within this context.
[debug] Files invalidated by inheriting from (external) com.nezasa.utils.throttling.ThrottlingSupport$: Set(); now invalidating by inheritance (internally).
[debug] Getting direct dependencies of all classes transitively invalidated by inheritance.
[debug] Getting classes that directly depend on (external) com.nezasa.utils.throttling.ThrottlingSupport$.
[debug] None of the modified names appears in source file of com.nezasa.integrations.wikivoyage.WikivoyageClient. This dependency is not being considered for invalidation.
[debug] None of the modified names appears in source file of com.nezasa.integrations.wikivoyage.WikivoyageClient.WikivoyageHttpConnectionConfig. This dependency is not being considered for invalidation.
[debug] No changes
[success] Total time: 0 s, completed Aug 11, 2020, 5:48:31 PM
[trip-builder] $ 
```

If I add breakpoint in `sbt.internal.inc.IncrementalNameHashingCommon#findAPIChange` where `NamesChange`  are created I can see the following 

![image](https://user-images.githubusercontent.com/943051/89927628-82bfb780-dbfe-11ea-8a8f-5ae0594fc686.png)

Interestingly `aNameHashes` has size 29 but `bNameHashes` has size 30, and the missong element is `logger` as the above logs also state... The only thing I can notice about `logger` is that it is a `org.slf4j.Logger` which is a Java Interface...

I will continue to investigate this code, but wanted to share this...

EDIT: Ofc that after editing the file a few times, I can no longer reproduce this...

**Comment by jtjeferreira** [comment]
After renaming `logger` to `logger2` I can reproduce this again (i.e the 1st compilation detects the changes and calls scalac correctly, but calling compile again detects some changes...)

```
[trip-builder] $ wikivoyage/compile
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] Copy resource mappings: 
[debug] 	
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 4 products, 1 sources, 5 libraries Map(${BASE}/modules/utils/throttling/src/main/scala/com/nezasa/utils/throttling/ThrottlingSupport.scala -> farm(d4efe49a767dd8f7))
[debug] current source = Set(${BASE}/modules/utils/throttling/src/main/scala/com/nezasa/utils/throttling/ThrottlingSupport.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set())
[debug] No changes
[debug] [zinc] IncrementalCompile -----------
[debug] IncrementalCompile.incrementalCompile
[debug] previous = Stamps for: 50 products, 5 sources, 16 libraries Map(${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/wikimarkupparser/package.scala -> farm(26929d773db886f0), ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/WikivoyageClient.scala -> farm(f26e61a1b7c3c1bc), ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/model/package.scala -> farm(b52d3341a989253a), ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/WikiVoyageArticleParser.scala -> farm(db0bb890f85cc214), ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/wikimarkupparser/WikimarkupParserBase.scala -> farm(2ef1f3e822b88d02))
[debug] current source = Set(${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/wikimarkupparser/package.scala, ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/WikivoyageClient.scala, ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/model/package.scala, ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/WikiVoyageArticleParser.scala, ${BASE}/modules/integrations/wikivoyage/src/main/scala/com/nezasa/integrations/wikivoyage/wikimarkupparser/WikimarkupParserBase.scala)
[debug] > initialChanges = InitialChanges(Changes(added = Set(), removed = Set(), changed = Set(), unmodified = ...),Set(),Set(),API Changes: Set(NamesChange(com.nezasa.utils.throttling.ThrottlingSupport$,ModifiedNames(changes = UsedName(logger2,[Default]), UsedName(logger,[Default])))))
[debug] The com.nezasa.utils.throttling.ThrottlingSupport$ has the following regular definitions changed:
[debug] 	UsedName(logger2,[Default]), UsedName(logger,[Default]).
[debug] All member reference dependencies will be considered within this context.
[debug] Files invalidated by inheriting from (external) com.nezasa.utils.throttling.ThrottlingSupport$: Set(); now invalidating by inheritance (internally).
[debug] Getting direct dependencies of all classes transitively invalidated by inheritance.
[debug] Getting classes that directly depend on (external) com.nezasa.utils.throttling.ThrottlingSupport$.
[debug] None of the modified names appears in source file of com.nezasa.integrations.wikivoyage.WikivoyageClient. This dependency is not being considered for invalidation.
[debug] None of the modified names appears in source file of com.nezasa.integrations.wikivoyage.WikivoyageClient.WikivoyageHttpConnectionConfig. This dependency is not being considered for invalidation.
[debug] No changes
[success] Total time: 2 s, completed Aug 11, 2020, 6:38:02 PM
```

Notice the `UsedName(logger2,[Default]), UsedName(logger,[Default]).` Maybe this happens because the incremental compile result from the first call to compile is not correctly saved, since it did not generate any changes in the sub project that depends on it?

**Comment by jtjeferreira** [comment]
I created a reproducer in https://github.com/jtjeferreira/zinc-issue-810

**Comment by jtjeferreira** [comment]
I tried to change sbt code to always save the analysis by removing this `if` https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/Defaults.scala#L1946 but still no luck...

@eed3si9n @eatkins @dwijnand any hints?

**Comment by eed3si9n** [comment]
Without looking into the details I'm not sure what's going on but I could point you to some directions to do some println debugging.. See for example around
https://github.com/sbt/zinc/blob/d8d05d87ba67e76bc4b66eefcd6eb81ea908f052/internal/zinc-core/src/main/scala/sbt/internal/inc/Incremental.scala#L386-L403

In your example, root subproject depends on core right?

The first round of compilation happens for `core` and `root`. Let's name Analysis of `root` at this state `a1`.

So second round of `compile` tries to invalidate classes based on `a1` from the first round. Compares the API:

```
[debug] The core.A has the following regular definitions changed:
[debug]         UsedName(a,[Default]), UsedName(b,[Default]).
```

Is it used? No. So nothing in `root` is invalidated. Then what happens is that `prev` = `a1` is return again as the Analysis. 

Now the third round of `compile`. Invalidate classes based on `a1`:

```
[debug] The core.A has the following regular definitions changed:
[debug]         UsedName(a,[Default]), UsedName(b,[Default]).
```

Is it used? No. So nothing in `root` is invalidated.

**Comment by jtjeferreira** [comment]
I agree with your analysis. I want to fix this by creating a new Analysis `a2` even if nothing in `root` is invalidated.

**Comment by eed3si9n** [comment]
@jtjeferreira That's the thing tho. If you created a new Analysis even for no-op `compile` that would incur extra IO, which could add up to a huge pause if you have 100 subprojects. 

https://github.com/sbt/sbt/issues/5570 was about things compiling twice. Do you also see overcompilation?

**Comment by jtjeferreira** [comment]
> @jtjeferreira That's the thing tho. If you created a new Analysis even for no-op `compile` that would incur extra IO, which could add up to a huge pause if you have 100 subprojects.
> 

I just need to do this when there are API changes in the sub project. The subsequent no-op `compile` dont need to create (or store) a new Analysis. I was looking around with a debugger and understand the problem, but dont have yet a clear way forward. Meanwhile I was going to add the reproducer as an scripted test, but I am not sure it is possible, since all the examples I see are single project

> [sbt/sbt#5570](https://github.com/sbt/sbt/issues/5570) was about things compiling twice. Do you also see overcompilation?

no, but a no-op `compile` in my work project reveals a few of these, which I feel makes the task slower

**Comment by eed3si9n** [comment]
> Meanwhile I was going to add the reproducer as an scripted test, but I am not sure it is possible, since all the examples I see are single project

Zinc has a mini build tool - https://github.com/sbt/zinc/blob/develop/zinc/src/sbt-test/macros/macro/build.json

**Comment by jtjeferreira** [comment]
> > Meanwhile I was going to add the reproducer as an scripted test, but I am not sure it is possible, since all the examples I see are single project
> 
> Zinc has a mini build tool - [https://github.com/sbt/zinc/blob/develop/zinc/src/sbt-test/macros/macro/build.json](https://github.com/sbt/zinc/blob/develop/zinc/src/sbt-test/macros/macro/build.json?rgh-link-date=2020-08-13T15%3A32%3A40Z)

Thanks, that was the missing piece. Now I just need to find a way to assert that the Analysis is (in)correct

**Comment by jtjeferreira** [comment]
@eed3si9n I opened a draft PR https://github.com/sbt/zinc/pull/880 with a scripted test, but now I am a bit lost. Some ideas that come to mind:
* Change `sbt.internal.inc.Incremental#incrementalCompile` to always call `incremental.cycle`; modify
`sbt.internal.inc.IncrementalCommon.CycleState` so that when we have external API changes we return a modified `Analysis` but dont call incremental compilation
https://github.com/sbt/zinc/blob/d8d05d87ba67e76bc4b66eefcd6eb81ea908f052/internal/zinc-core/src/main/scala/sbt/internal/inc/Incremental.scala#L386-L403 https://github.com/sbt/zinc/blob/d8d05d87ba67e76bc4b66eefcd6eb81ea908f052/internal/zinc-core/src/main/scala/sbt/internal/inc/IncrementalCommon.scala#L78-L79
* Change `sbt.internal.inc.Incremental#incrementalCompile` to return a modified `Analysis`, but AFAICT the logic to create a new Analysis is inside `CycleState`...

**Comment by eed3si9n** [comment]
"cycle" usually means a round of compilation, so I'd suggest you you make a new method for it?
You could try appending new APIs using `Analysis#copy` or something.

https://github.com/sbt/zinc/blob/develop/internal/zinc-core/src/main/scala/sbt/internal/inc/APIs.scala

```scala
else {
   if (options.pipelining) 
     writeEarlyOut(lookup, progress, earlyOutput, previous, new java.util.HashSet) 
  if (hasSubprojectChange) previous.copy(apis = previous.apis ++ <stuff here>)
  else previous 
}
```
