### ISSUE TITLE
SAM type change causes undercompilation

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#830]
This is yet another example of Zinc lagging Scala language spec change. 
https://www.scala-lang.org/news/2.12.0/#lambda-syntax-for-sam-types

## steps

Haven't minimized it but I noticed while coding. First you have a Java interface in one subproject.

```java
import java.nio.file.Path;
import java.util.Optional;

public interface SingleOutput {
    public Path getOutputDirectory();

    public default Optional<Path> getSingleOutput() {
        return Optional.of(getOutputDirectory());
    }
}
```

In another subproject, use it as  SAM-type lambda:

```scala
val output: SingleOutput = () => RootFilePath.resolve("out")
```

Then change the Java interface..

```java
import java.io.File;
import java.util.Optional;

public interface SingleOutput {
    public File getOutputDirectory();

    public default Optional< File > getSingleOutput() {
        return Optional.of(getOutputDirectory());
    }
}
```

## problem

The Scala code is not invalidated. So locally `compile` keeps succeeding. On CI the build fails if it's compiled from scratch.

## expectation

Invalidate correctly.

**Comment by smarter** [comment]
Fixed in Scala 3 with https://github.com/lampepfl/dotty/pull/16996.

**Comment by smarter** [comment]
Interesting, this got closed from a commit in another repo, but should be kept open since it's still an issue in scala 2.
