### ISSUE TITLE
Really remove resident compiler (CompilerCache)

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#835]
Ref https://github.com/sbt/sbt/issues/1287
Ref https://github.com/sbt/zinc/issues/340

Maybe this is a good opportunity to remove `CompilerCache` in general.

It was turned off by default 

```scala
compilerCache <<= state map { _ get Keys.stateCompilerCache getOrElse compiler.CompilerCache.fresh },
```

in https://github.com/sbt/sbt/commit/6769c942083d37c7729adcd26f43d441ab89ecf1 when it was first introduced in 2012 . There was an attempt to remove it in 2017 https://github.com/sbt/zinc/pull/345, but it didn't go all the way. So retronym added a TODO to remove it in 2019 when the compiler became `java.io.Closable` in https://github.com/scala/scala/pull/7366 - https://github.com/sbt/zinc/pull/643.

_Originally posted by @eed3si9n in https://github.com/sbt/zinc/pull/829#issuecomment-658245805_

**Comment by eed3si9n** [comment]
We can implement FreshCompilerCache and return that for all 3 methods in `CompilerCache.java` - https://github.com/sbt/zinc/blob/ed1f9f0156483c4021946699b4dbfed59ec68c1c/internal/zinc-compile-core/src/main/java/xsbti/compile/CompilerCache.java

For `CompilerInterface2`, remove `cache` parameter. This makes `CachedCompiler2` as the concept unnecessary.

**Comment by dwijnand** [comment]
The return of #711!

**Comment by lrytz** [comment]
Yeah, there were some concerns about removing it at #711. Personally I'm in favor of the removal.

**Comment by eed3si9n** [comment]
Now that I'm working in and around compiler-interface and -bridge, I see that resident compiler makes the API unnecessarily indirect. I don't think it's worth it if no one has used it seriously in 8 years.

@jvican @Duhemm Is the use case of resident compiler in Bloop an active use case? Looks like it's using FreshCompilerCache here - https://github.com/scalacenter/bloop/blob/2e49bd2222b4979666924ce465302cd0636c181d/backend/src/main/scala/bloop/Compiler.scala#L317
