### ISSUE TITLE
Scripted doesn't support multiprojects

### ISSUE THREAD

**Issue by gkossakowski** [sbt/zinc#84]
This doesn't let us test multi-project support in incremental compiler.

Maybe the solution would be to port such tests to be a plain code that calls into IncHandler directly?

**Comment by eed3si9n** [comment]
In the long run maybe we should run some integration test that runs sbt with freshly compiled zinc:
1. so we can check that zinc didn't break API points for sbt.
2. and be able to run more sophisticated scripted tests

**Comment by gkossakowski** [comment]
This is a pretty good idea on its own but I'd like something more lightweight for testing multi-project support that has a fast turnaround time. Those tests should be really fast to run.

Fast turnaround was my original motivation for introducing specs2-based tests as an alternative to scripted tests.

**Comment by jvican** [comment]
Multi project support was already implemented and nobody closed this ticket. An example is `subproject-dependency`. Here's the proof:
  
```
{
  "projects": [
    {
      "name": "use",
      "dependsOn": ["dep"]
    },
    {
      "name": "dep"
    }
  ]
}
```
  
Unless I'm missing something, this is done. I'm closing it, feel free to reopen if I'm wrong or the motivation of this ticket was different than the multi-project support I refer to.

**Comment by eed3si9n** [comment]
Yes. I fixed in https://github.com/sbt/zinc/pull/208, but didn't close it.
