### ISSUE TITLE
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.

### ISSUE THREAD

**Issue by smrititaneja18** [sbt/zinc#846]
Anyone can help me with the above titled issue?

**Comment by eed3si9n** [comment]
We use GitHub issue mostly to track bugs and discuss feature or bugs on Zinc. Without a way to reproduce the problem on our machines, I don't think we can identify the issue. See https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md#what-to-report
