### ISSUE TITLE
checkExists should be renamed to checkNameExistsInClass

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#894]
Ref https://github.com/sbt/zinc/pull/880

## problem

The name `checkExists` is a little vague.

## expectation

It would be more clear if it was something like `checkNameExistsInClass`. I found the test cases at the bottom confusing to read without looking at the source code.

_Originally posted by @eatkins in https://github.com/sbt/zinc/pull/880#discussion_r474132514_

**Comment by dwijnand** [comment]
Yeah, it could use a more clarifying name, agreed.
