### ISSUE TITLE
scalatest conversion

### ISSUE THREAD

**Issue by eed3si9n** [sbt/zinc#9]
@Duhemm This is a reminder on adding `assert` around `===`.

**Comment by jvican** [comment]
Can you elaborate @eed3si9n on what you wanted here?

**Comment by eed3si9n** [comment]
Our unit tests used to use Specs2 but we converted to ScalaTest.
One of the differences is that ScalaTest requires assert around === to take effect, especially if there are multiple of them in an example, and I think the ones converted by Martin were missing some.

**Comment by jvican** [comment]
@Duhemm Do you know which tests are mising the `assert`?

**Comment by Duhemm** [comment]
@jvican I don't know, I think it has been fixed already? I'll check.
