### ISSUE TITLE
Reported problems are always empty on VirtualFiles

### ISSUE THREAD

**Issue by adpi2** [sbt/zinc#930]
## steps

- Create an sbt project
- Add a warning inside a source file:
```scala
def foo() = ???
foo // deprecation warning on scala 2.13.3 with -deprecation flag 
```
- Print the reported problems in `compile.value`

```scala
compile.value.getAnalysis.readSourceInfos.foreach {
  case (_, infos) =>
    println(infos.getReportedProblems.size)
    println(infos.getUnreportedProblems.size)
}
```

## problem

The reported problems are empty

## expectation

The reported problems should contain the warning

## notes

The bug is located in the `AnalysisCallback` class:

https://github.com/sbt/zinc/blob/52c63b3a146b1e641897dda8055662311550d6c9/internal/zinc-core/src/main/scala/sbt/internal/inc/Incremental.scala#L676-L690

Here `pos.sourcePath` contains an absolute path whereas in the following lines `src` contains a `VirtualFile` path.

https://github.com/sbt/zinc/blob/52c63b3a146b1e641897dda8055662311550d6c9/internal/zinc-core/src/main/scala/sbt/internal/inc/Incremental.scala#L963-L967

All `reported` and `unreported` are lost when the `Analysis` is built.

Fixing this bug can help fixing:
https://github.com/sbt/sbt/issues/5937
https://github.com/sbt/sbt/issues/5950

**Comment by adpi2** [comment]
Actually the `position.sourcePath` is a `VirtualFile` ref until the `LoggedReporter` transforms it through the `sourcePositionMapper` given by sbt. This `sourcePositionMapper` converts `position.sourcePath` to absolute for better logging.

When the `Reporter` is asked for the reported problems by the `AnalysisCallback`, it should return the original positions and not the transformed ones.

**Comment by eed3si9n** [comment]
> When the `Reporter` is asked for the reported problems by the `AnalysisCallback`, it should return the original positions and not the transformed ones.

Yea. I think you found the core of this issue. Maybe there should be a parameter to toggle this behavior? (Not sure if that makes sense)
