### ISSUE TITLE
ScalaInstance constructor deprecated in 1.5.0 looks broken

### ISSUE THREAD

**Issue by slandelle** [sbt/zinc#972]
## steps

Check code: https://github.com/sbt/zinc/blob/v1.5.0/internal/zinc-classpath/src/main/scala/sbt/internal/inc/ScalaInstance.scala#L61-L62

## problem

`this` constructor is called without using named parameters. It looks like some parameters are inverted and the compilerJar parameter is lost.

## expectation

It think it should be:

```scala
    this(
      version,
      loader,
      loader,
      loaderLibraryOnly,
      Array(libraryJar),
      Array(compilerJar),
      allJars
      explicitActual
    )
```

**Comment by eed3si9n** [comment]
Thanks for the report!

**Comment by adpi2** [comment]
Thanks @slandelle!

Indeed something seems to be wrong in this constructor.
