### ISSUE TITLE
Performance evaluation of clean builds with class-based deps tracking

### ISSUE THREAD

**Issue by gkossakowski** [sbt/zinc#99]
This is an issue where I'll track performance tests of the current HEAD of zinc (with class-based deps tracking merged). In this issue, I'm interested in measuring the overhead of incremental compiler added to Scalac's raw performance. I'll get the numbers using `;clean;compile` command from sbt 1.0. The base line for comparison is sbt 0.13.11.

The tasks for performance evaluation:
- [ ] check compilation speed of compiling the Scala compiler. We're interested in the performance on this code base due to high number of inner classes and heavy use of an inheritance (for cake pattern).
- [ ] check compilation speed on https://github.com/gkossakowski/sbt-slow-compile which heavily relies on classpath lookup performance

**Comment by jvican** [comment]
This is not something actionable, so closing
